/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_SIGNATURE_H
#define _MOCK_SIGNATURE_H

#include "unity.h"
#include "signature.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_signature_Init(void);
void mock_signature_Destroy(void);
void mock_signature_Verify(void);




#define Signature_verification_IgnoreAndReturn(cmock_retval) Signature_verification_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void Signature_verification_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, signatureType_E cmock_to_return);
#define Signature_verification_StopIgnore() Signature_verification_CMockStopIgnore()
void Signature_verification_CMockStopIgnore(void);
#define Signature_verification_ExpectAnyArgsAndReturn(cmock_retval) Signature_verification_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void Signature_verification_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, signatureType_E cmock_to_return);
#define Signature_verification_ExpectAndReturn(signature, cmock_retval) Signature_verification_CMockExpectAndReturn(__LINE__, signature, cmock_retval)
void Signature_verification_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const signature_S* signature, signatureType_E cmock_to_return);
typedef signatureType_E (* CMOCK_Signature_verification_CALLBACK)(const signature_S* signature, int cmock_num_calls);
void Signature_verification_AddCallback(CMOCK_Signature_verification_CALLBACK Callback);
void Signature_verification_Stub(CMOCK_Signature_verification_CALLBACK Callback);
#define Signature_verification_StubWithCallback Signature_verification_Stub
#define Signature_verification_ExpectWithArrayAndReturn(signature, signature_Depth, cmock_retval) Signature_verification_CMockExpectWithArrayAndReturn(__LINE__, signature, signature_Depth, cmock_retval)
void Signature_verification_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const signature_S* signature, int signature_Depth, signatureType_E cmock_to_return);
#define Signature_verification_IgnoreArg_signature() Signature_verification_CMockIgnoreArg_signature(__LINE__)
void Signature_verification_CMockIgnoreArg_signature(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
