/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_SYSTEM_CLOCK_ADAPTER_H
#define _MOCK_SYSTEM_CLOCK_ADAPTER_H

#include "unity.h"
#include "system_clock_adapter.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_system_clock_adapter_Init(void);
void mock_system_clock_adapter_Destroy(void);
void mock_system_clock_adapter_Verify(void);




#define SystemClock_Config_Ignore() SystemClock_Config_CMockIgnore()
void SystemClock_Config_CMockIgnore(void);
#define SystemClock_Config_StopIgnore() SystemClock_Config_CMockStopIgnore()
void SystemClock_Config_CMockStopIgnore(void);
#define SystemClock_Config_Expect() SystemClock_Config_CMockExpect(__LINE__)
void SystemClock_Config_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_SystemClock_Config_CALLBACK)(int cmock_num_calls);
void SystemClock_Config_AddCallback(CMOCK_SystemClock_Config_CALLBACK Callback);
void SystemClock_Config_Stub(CMOCK_SystemClock_Config_CALLBACK Callback);
#define SystemClock_Config_StubWithCallback SystemClock_Config_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
