/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_signature.h"

static const char* CMockString_Signature_verification = "Signature_verification";
static const char* CMockString_signature = "signature";

typedef struct _CMOCK_Signature_verification_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  signatureType_E ReturnVal;
  const signature_S* Expected_signature;
  int Expected_signature_Depth;
  char IgnoreArg_signature;

} CMOCK_Signature_verification_CALL_INSTANCE;

static struct mock_signatureInstance
{
  char Signature_verification_IgnoreBool;
  signatureType_E Signature_verification_FinalReturn;
  char Signature_verification_CallbackBool;
  CMOCK_Signature_verification_CALLBACK Signature_verification_CallbackFunctionPointer;
  int Signature_verification_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Signature_verification_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_signature_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.Signature_verification_CallInstance;
  if (Mock.Signature_verification_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Signature_verification);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Signature_verification_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_signature_Init(void)
{
  mock_signature_Destroy();
}

void mock_signature_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

signatureType_E Signature_verification(const signature_S* signature)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Signature_verification_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Signature_verification);
  cmock_call_instance = (CMOCK_Signature_verification_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Signature_verification_CallInstance);
  Mock.Signature_verification_CallInstance = CMock_Guts_MemNext(Mock.Signature_verification_CallInstance);
  if (Mock.Signature_verification_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.Signature_verification_FinalReturn;
    memcpy((void*)(&Mock.Signature_verification_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(signatureType_E[sizeof(cmock_call_instance->ReturnVal) == sizeof(signatureType_E) ? 1 : -1])); /* add signatureType_E to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.Signature_verification_CallbackBool &&
      Mock.Signature_verification_CallbackFunctionPointer != NULL)
  {
    signatureType_E cmock_cb_ret = Mock.Signature_verification_CallbackFunctionPointer(signature, Mock.Signature_verification_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_signature)
  {
    UNITY_SET_DETAILS(CMockString_Signature_verification,CMockString_signature);
    if (cmock_call_instance->Expected_signature == NULL)
      { UNITY_TEST_ASSERT_NULL(signature, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_signature), (void*)(signature), sizeof(const signature_S), cmock_call_instance->Expected_signature_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.Signature_verification_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.Signature_verification_CallbackFunctionPointer(signature, Mock.Signature_verification_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_Signature_verification(CMOCK_Signature_verification_CALL_INSTANCE* cmock_call_instance, const signature_S* signature, int signature_Depth);
void CMockExpectParameters_Signature_verification(CMOCK_Signature_verification_CALL_INSTANCE* cmock_call_instance, const signature_S* signature, int signature_Depth)
{
  cmock_call_instance->Expected_signature = signature;
  cmock_call_instance->Expected_signature_Depth = signature_Depth;
  cmock_call_instance->IgnoreArg_signature = 0;
}

void Signature_verification_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, signatureType_E cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Signature_verification_CALL_INSTANCE));
  CMOCK_Signature_verification_CALL_INSTANCE* cmock_call_instance = (CMOCK_Signature_verification_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Signature_verification_CallInstance = CMock_Guts_MemChain(Mock.Signature_verification_CallInstance, cmock_guts_index);
  Mock.Signature_verification_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.Signature_verification_IgnoreBool = (char)1;
}

void Signature_verification_CMockStopIgnore(void)
{
  if(Mock.Signature_verification_IgnoreBool)
    Mock.Signature_verification_CallInstance = CMock_Guts_MemNext(Mock.Signature_verification_CallInstance);
  Mock.Signature_verification_IgnoreBool = (char)0;
}

void Signature_verification_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, signatureType_E cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Signature_verification_CALL_INSTANCE));
  CMOCK_Signature_verification_CALL_INSTANCE* cmock_call_instance = (CMOCK_Signature_verification_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Signature_verification_CallInstance = CMock_Guts_MemChain(Mock.Signature_verification_CallInstance, cmock_guts_index);
  Mock.Signature_verification_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void Signature_verification_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const signature_S* signature, signatureType_E cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Signature_verification_CALL_INSTANCE));
  CMOCK_Signature_verification_CALL_INSTANCE* cmock_call_instance = (CMOCK_Signature_verification_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Signature_verification_CallInstance = CMock_Guts_MemChain(Mock.Signature_verification_CallInstance, cmock_guts_index);
  Mock.Signature_verification_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_Signature_verification(cmock_call_instance, signature, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(signatureType_E[sizeof(cmock_to_return) == sizeof(signatureType_E) ? 1 : -1])); /* add signatureType_E to :treat_as_array if this causes an error */
}

void Signature_verification_AddCallback(CMOCK_Signature_verification_CALLBACK Callback)
{
  Mock.Signature_verification_IgnoreBool = (char)0;
  Mock.Signature_verification_CallbackBool = (char)1;
  Mock.Signature_verification_CallbackFunctionPointer = Callback;
}

void Signature_verification_Stub(CMOCK_Signature_verification_CALLBACK Callback)
{
  Mock.Signature_verification_IgnoreBool = (char)0;
  Mock.Signature_verification_CallbackBool = (char)0;
  Mock.Signature_verification_CallbackFunctionPointer = Callback;
}

void Signature_verification_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const signature_S* signature, int signature_Depth, signatureType_E cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Signature_verification_CALL_INSTANCE));
  CMOCK_Signature_verification_CALL_INSTANCE* cmock_call_instance = (CMOCK_Signature_verification_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Signature_verification_CallInstance = CMock_Guts_MemChain(Mock.Signature_verification_CallInstance, cmock_guts_index);
  Mock.Signature_verification_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_Signature_verification(cmock_call_instance, signature, signature_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Signature_verification_CMockIgnoreArg_signature(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_Signature_verification_CALL_INSTANCE* cmock_call_instance = (CMOCK_Signature_verification_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Signature_verification_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_signature = 1;
}

