/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_security.h"

static const char* CMockString_Security_decrypt = "Security_decrypt";
static const char* CMockString_Security_getClientSecurityDataJson = "Security_getClientSecurityDataJson";
static const char* CMockString_Security_isSecured = "Security_isSecured";
static const char* CMockString_Security_setServerSecurityDataJson = "Security_setServerSecurityDataJson";
static const char* CMockString_Security_wipeKeys = "Security_wipeKeys";
static const char* CMockString_buffer = "buffer";
static const char* CMockString_buffer_size = "buffer_size";
static const char* CMockString_cipher_data = "cipher_data";
static const char* CMockString_data_length = "data_length";
static const char* CMockString_mac = "mac";
static const char* CMockString_nonce = "nonce";
static const char* CMockString_plain_data = "plain_data";

typedef struct _CMOCK_Security_setServerSecurityDataJson_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;
  char* Expected_buffer;
  uint16_t Expected_buffer_size;
  char ReturnThruPtr_buffer_Used;
  char const* ReturnThruPtr_buffer_Val;
  size_t ReturnThruPtr_buffer_Size;
  char IgnoreArg_buffer;
  char IgnoreArg_buffer_size;

} CMOCK_Security_setServerSecurityDataJson_CALL_INSTANCE;

typedef struct _CMOCK_Security_getClientSecurityDataJson_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;
  char* Expected_buffer;
  uint16_t Expected_buffer_size;
  char ReturnThruPtr_buffer_Used;
  char const* ReturnThruPtr_buffer_Val;
  size_t ReturnThruPtr_buffer_Size;
  char IgnoreArg_buffer;
  char IgnoreArg_buffer_size;

} CMOCK_Security_getClientSecurityDataJson_CALL_INSTANCE;

typedef struct _CMOCK_Security_isSecured_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;

} CMOCK_Security_isSecured_CALL_INSTANCE;

typedef struct _CMOCK_Security_decrypt_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;
  const uint8_t* Expected_mac;
  const uint8_t* Expected_nonce;
  const uint8_t* Expected_cipher_data;
  uint8_t* Expected_plain_data;
  uint16_t Expected_data_length;
  int Expected_mac_Depth;
  int Expected_nonce_Depth;
  int Expected_cipher_data_Depth;
  int Expected_plain_data_Depth;
  char ReturnThruPtr_plain_data_Used;
  uint8_t const* ReturnThruPtr_plain_data_Val;
  size_t ReturnThruPtr_plain_data_Size;
  char IgnoreArg_mac;
  char IgnoreArg_nonce;
  char IgnoreArg_cipher_data;
  char IgnoreArg_plain_data;
  char IgnoreArg_data_length;

} CMOCK_Security_decrypt_CALL_INSTANCE;

typedef struct _CMOCK_Security_wipeKeys_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_Security_wipeKeys_CALL_INSTANCE;

static struct mock_securityInstance
{
  char Security_setServerSecurityDataJson_IgnoreBool;
  bool Security_setServerSecurityDataJson_FinalReturn;
  char Security_setServerSecurityDataJson_CallbackBool;
  CMOCK_Security_setServerSecurityDataJson_CALLBACK Security_setServerSecurityDataJson_CallbackFunctionPointer;
  int Security_setServerSecurityDataJson_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Security_setServerSecurityDataJson_CallInstance;
  char Security_getClientSecurityDataJson_IgnoreBool;
  bool Security_getClientSecurityDataJson_FinalReturn;
  char Security_getClientSecurityDataJson_CallbackBool;
  CMOCK_Security_getClientSecurityDataJson_CALLBACK Security_getClientSecurityDataJson_CallbackFunctionPointer;
  int Security_getClientSecurityDataJson_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Security_getClientSecurityDataJson_CallInstance;
  char Security_isSecured_IgnoreBool;
  bool Security_isSecured_FinalReturn;
  char Security_isSecured_CallbackBool;
  CMOCK_Security_isSecured_CALLBACK Security_isSecured_CallbackFunctionPointer;
  int Security_isSecured_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Security_isSecured_CallInstance;
  char Security_decrypt_IgnoreBool;
  bool Security_decrypt_FinalReturn;
  char Security_decrypt_CallbackBool;
  CMOCK_Security_decrypt_CALLBACK Security_decrypt_CallbackFunctionPointer;
  int Security_decrypt_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Security_decrypt_CallInstance;
  char Security_wipeKeys_IgnoreBool;
  char Security_wipeKeys_CallbackBool;
  CMOCK_Security_wipeKeys_CALLBACK Security_wipeKeys_CallbackFunctionPointer;
  int Security_wipeKeys_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Security_wipeKeys_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_security_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.Security_setServerSecurityDataJson_CallInstance;
  if (Mock.Security_setServerSecurityDataJson_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Security_setServerSecurityDataJson);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Security_setServerSecurityDataJson_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Security_getClientSecurityDataJson_CallInstance;
  if (Mock.Security_getClientSecurityDataJson_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Security_getClientSecurityDataJson);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Security_getClientSecurityDataJson_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Security_isSecured_CallInstance;
  if (Mock.Security_isSecured_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Security_isSecured);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Security_isSecured_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Security_decrypt_CallInstance;
  if (Mock.Security_decrypt_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Security_decrypt);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Security_decrypt_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Security_wipeKeys_CallInstance;
  if (Mock.Security_wipeKeys_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Security_wipeKeys);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Security_wipeKeys_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_security_Init(void)
{
  mock_security_Destroy();
}

void mock_security_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

bool Security_setServerSecurityDataJson(char* buffer, uint16_t buffer_size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Security_setServerSecurityDataJson_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Security_setServerSecurityDataJson);
  cmock_call_instance = (CMOCK_Security_setServerSecurityDataJson_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Security_setServerSecurityDataJson_CallInstance);
  Mock.Security_setServerSecurityDataJson_CallInstance = CMock_Guts_MemNext(Mock.Security_setServerSecurityDataJson_CallInstance);
  if (Mock.Security_setServerSecurityDataJson_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.Security_setServerSecurityDataJson_FinalReturn;
    Mock.Security_setServerSecurityDataJson_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.Security_setServerSecurityDataJson_CallbackBool &&
      Mock.Security_setServerSecurityDataJson_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.Security_setServerSecurityDataJson_CallbackFunctionPointer(buffer, buffer_size, Mock.Security_setServerSecurityDataJson_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_buffer)
  {
    UNITY_SET_DETAILS(CMockString_Security_setServerSecurityDataJson,CMockString_buffer);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_buffer, buffer, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_buffer_size)
  {
    UNITY_SET_DETAILS(CMockString_Security_setServerSecurityDataJson,CMockString_buffer_size);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_buffer_size, buffer_size, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.Security_setServerSecurityDataJson_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.Security_setServerSecurityDataJson_CallbackFunctionPointer(buffer, buffer_size, Mock.Security_setServerSecurityDataJson_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_buffer_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(buffer, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)buffer, (const void*)cmock_call_instance->ReturnThruPtr_buffer_Val,
      cmock_call_instance->ReturnThruPtr_buffer_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_Security_setServerSecurityDataJson(CMOCK_Security_setServerSecurityDataJson_CALL_INSTANCE* cmock_call_instance, char* buffer, uint16_t buffer_size);
void CMockExpectParameters_Security_setServerSecurityDataJson(CMOCK_Security_setServerSecurityDataJson_CALL_INSTANCE* cmock_call_instance, char* buffer, uint16_t buffer_size)
{
  cmock_call_instance->Expected_buffer = buffer;
  cmock_call_instance->IgnoreArg_buffer = 0;
  cmock_call_instance->ReturnThruPtr_buffer_Used = 0;
  cmock_call_instance->Expected_buffer_size = buffer_size;
  cmock_call_instance->IgnoreArg_buffer_size = 0;
}

void Security_setServerSecurityDataJson_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Security_setServerSecurityDataJson_CALL_INSTANCE));
  CMOCK_Security_setServerSecurityDataJson_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_setServerSecurityDataJson_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Security_setServerSecurityDataJson_CallInstance = CMock_Guts_MemChain(Mock.Security_setServerSecurityDataJson_CallInstance, cmock_guts_index);
  Mock.Security_setServerSecurityDataJson_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.Security_setServerSecurityDataJson_IgnoreBool = (char)1;
}

void Security_setServerSecurityDataJson_CMockStopIgnore(void)
{
  if(Mock.Security_setServerSecurityDataJson_IgnoreBool)
    Mock.Security_setServerSecurityDataJson_CallInstance = CMock_Guts_MemNext(Mock.Security_setServerSecurityDataJson_CallInstance);
  Mock.Security_setServerSecurityDataJson_IgnoreBool = (char)0;
}

void Security_setServerSecurityDataJson_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Security_setServerSecurityDataJson_CALL_INSTANCE));
  CMOCK_Security_setServerSecurityDataJson_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_setServerSecurityDataJson_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Security_setServerSecurityDataJson_CallInstance = CMock_Guts_MemChain(Mock.Security_setServerSecurityDataJson_CallInstance, cmock_guts_index);
  Mock.Security_setServerSecurityDataJson_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void Security_setServerSecurityDataJson_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* buffer, uint16_t buffer_size, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Security_setServerSecurityDataJson_CALL_INSTANCE));
  CMOCK_Security_setServerSecurityDataJson_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_setServerSecurityDataJson_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Security_setServerSecurityDataJson_CallInstance = CMock_Guts_MemChain(Mock.Security_setServerSecurityDataJson_CallInstance, cmock_guts_index);
  Mock.Security_setServerSecurityDataJson_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_Security_setServerSecurityDataJson(cmock_call_instance, buffer, buffer_size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Security_setServerSecurityDataJson_AddCallback(CMOCK_Security_setServerSecurityDataJson_CALLBACK Callback)
{
  Mock.Security_setServerSecurityDataJson_IgnoreBool = (char)0;
  Mock.Security_setServerSecurityDataJson_CallbackBool = (char)1;
  Mock.Security_setServerSecurityDataJson_CallbackFunctionPointer = Callback;
}

void Security_setServerSecurityDataJson_Stub(CMOCK_Security_setServerSecurityDataJson_CALLBACK Callback)
{
  Mock.Security_setServerSecurityDataJson_IgnoreBool = (char)0;
  Mock.Security_setServerSecurityDataJson_CallbackBool = (char)0;
  Mock.Security_setServerSecurityDataJson_CallbackFunctionPointer = Callback;
}

void Security_setServerSecurityDataJson_CMockReturnMemThruPtr_buffer(UNITY_LINE_TYPE cmock_line, char const* buffer, size_t cmock_size)
{
  CMOCK_Security_setServerSecurityDataJson_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_setServerSecurityDataJson_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Security_setServerSecurityDataJson_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_buffer_Used = 1;
  cmock_call_instance->ReturnThruPtr_buffer_Val = buffer;
  cmock_call_instance->ReturnThruPtr_buffer_Size = cmock_size;
}

void Security_setServerSecurityDataJson_CMockIgnoreArg_buffer(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_Security_setServerSecurityDataJson_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_setServerSecurityDataJson_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Security_setServerSecurityDataJson_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_buffer = 1;
}

void Security_setServerSecurityDataJson_CMockIgnoreArg_buffer_size(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_Security_setServerSecurityDataJson_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_setServerSecurityDataJson_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Security_setServerSecurityDataJson_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_buffer_size = 1;
}

bool Security_getClientSecurityDataJson(char* buffer, uint16_t buffer_size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Security_getClientSecurityDataJson_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Security_getClientSecurityDataJson);
  cmock_call_instance = (CMOCK_Security_getClientSecurityDataJson_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Security_getClientSecurityDataJson_CallInstance);
  Mock.Security_getClientSecurityDataJson_CallInstance = CMock_Guts_MemNext(Mock.Security_getClientSecurityDataJson_CallInstance);
  if (Mock.Security_getClientSecurityDataJson_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.Security_getClientSecurityDataJson_FinalReturn;
    Mock.Security_getClientSecurityDataJson_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.Security_getClientSecurityDataJson_CallbackBool &&
      Mock.Security_getClientSecurityDataJson_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.Security_getClientSecurityDataJson_CallbackFunctionPointer(buffer, buffer_size, Mock.Security_getClientSecurityDataJson_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_buffer)
  {
    UNITY_SET_DETAILS(CMockString_Security_getClientSecurityDataJson,CMockString_buffer);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_buffer, buffer, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_buffer_size)
  {
    UNITY_SET_DETAILS(CMockString_Security_getClientSecurityDataJson,CMockString_buffer_size);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_buffer_size, buffer_size, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.Security_getClientSecurityDataJson_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.Security_getClientSecurityDataJson_CallbackFunctionPointer(buffer, buffer_size, Mock.Security_getClientSecurityDataJson_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_buffer_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(buffer, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)buffer, (const void*)cmock_call_instance->ReturnThruPtr_buffer_Val,
      cmock_call_instance->ReturnThruPtr_buffer_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_Security_getClientSecurityDataJson(CMOCK_Security_getClientSecurityDataJson_CALL_INSTANCE* cmock_call_instance, char* buffer, uint16_t buffer_size);
void CMockExpectParameters_Security_getClientSecurityDataJson(CMOCK_Security_getClientSecurityDataJson_CALL_INSTANCE* cmock_call_instance, char* buffer, uint16_t buffer_size)
{
  cmock_call_instance->Expected_buffer = buffer;
  cmock_call_instance->IgnoreArg_buffer = 0;
  cmock_call_instance->ReturnThruPtr_buffer_Used = 0;
  cmock_call_instance->Expected_buffer_size = buffer_size;
  cmock_call_instance->IgnoreArg_buffer_size = 0;
}

void Security_getClientSecurityDataJson_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Security_getClientSecurityDataJson_CALL_INSTANCE));
  CMOCK_Security_getClientSecurityDataJson_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_getClientSecurityDataJson_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Security_getClientSecurityDataJson_CallInstance = CMock_Guts_MemChain(Mock.Security_getClientSecurityDataJson_CallInstance, cmock_guts_index);
  Mock.Security_getClientSecurityDataJson_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.Security_getClientSecurityDataJson_IgnoreBool = (char)1;
}

void Security_getClientSecurityDataJson_CMockStopIgnore(void)
{
  if(Mock.Security_getClientSecurityDataJson_IgnoreBool)
    Mock.Security_getClientSecurityDataJson_CallInstance = CMock_Guts_MemNext(Mock.Security_getClientSecurityDataJson_CallInstance);
  Mock.Security_getClientSecurityDataJson_IgnoreBool = (char)0;
}

void Security_getClientSecurityDataJson_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Security_getClientSecurityDataJson_CALL_INSTANCE));
  CMOCK_Security_getClientSecurityDataJson_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_getClientSecurityDataJson_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Security_getClientSecurityDataJson_CallInstance = CMock_Guts_MemChain(Mock.Security_getClientSecurityDataJson_CallInstance, cmock_guts_index);
  Mock.Security_getClientSecurityDataJson_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void Security_getClientSecurityDataJson_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* buffer, uint16_t buffer_size, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Security_getClientSecurityDataJson_CALL_INSTANCE));
  CMOCK_Security_getClientSecurityDataJson_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_getClientSecurityDataJson_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Security_getClientSecurityDataJson_CallInstance = CMock_Guts_MemChain(Mock.Security_getClientSecurityDataJson_CallInstance, cmock_guts_index);
  Mock.Security_getClientSecurityDataJson_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_Security_getClientSecurityDataJson(cmock_call_instance, buffer, buffer_size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Security_getClientSecurityDataJson_AddCallback(CMOCK_Security_getClientSecurityDataJson_CALLBACK Callback)
{
  Mock.Security_getClientSecurityDataJson_IgnoreBool = (char)0;
  Mock.Security_getClientSecurityDataJson_CallbackBool = (char)1;
  Mock.Security_getClientSecurityDataJson_CallbackFunctionPointer = Callback;
}

void Security_getClientSecurityDataJson_Stub(CMOCK_Security_getClientSecurityDataJson_CALLBACK Callback)
{
  Mock.Security_getClientSecurityDataJson_IgnoreBool = (char)0;
  Mock.Security_getClientSecurityDataJson_CallbackBool = (char)0;
  Mock.Security_getClientSecurityDataJson_CallbackFunctionPointer = Callback;
}

void Security_getClientSecurityDataJson_CMockReturnMemThruPtr_buffer(UNITY_LINE_TYPE cmock_line, char const* buffer, size_t cmock_size)
{
  CMOCK_Security_getClientSecurityDataJson_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_getClientSecurityDataJson_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Security_getClientSecurityDataJson_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_buffer_Used = 1;
  cmock_call_instance->ReturnThruPtr_buffer_Val = buffer;
  cmock_call_instance->ReturnThruPtr_buffer_Size = cmock_size;
}

void Security_getClientSecurityDataJson_CMockIgnoreArg_buffer(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_Security_getClientSecurityDataJson_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_getClientSecurityDataJson_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Security_getClientSecurityDataJson_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_buffer = 1;
}

void Security_getClientSecurityDataJson_CMockIgnoreArg_buffer_size(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_Security_getClientSecurityDataJson_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_getClientSecurityDataJson_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Security_getClientSecurityDataJson_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_buffer_size = 1;
}

bool Security_isSecured(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Security_isSecured_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Security_isSecured);
  cmock_call_instance = (CMOCK_Security_isSecured_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Security_isSecured_CallInstance);
  Mock.Security_isSecured_CallInstance = CMock_Guts_MemNext(Mock.Security_isSecured_CallInstance);
  if (Mock.Security_isSecured_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.Security_isSecured_FinalReturn;
    Mock.Security_isSecured_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.Security_isSecured_CallbackBool &&
      Mock.Security_isSecured_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.Security_isSecured_CallbackFunctionPointer(Mock.Security_isSecured_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.Security_isSecured_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.Security_isSecured_CallbackFunctionPointer(Mock.Security_isSecured_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void Security_isSecured_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Security_isSecured_CALL_INSTANCE));
  CMOCK_Security_isSecured_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_isSecured_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Security_isSecured_CallInstance = CMock_Guts_MemChain(Mock.Security_isSecured_CallInstance, cmock_guts_index);
  Mock.Security_isSecured_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.Security_isSecured_IgnoreBool = (char)1;
}

void Security_isSecured_CMockStopIgnore(void)
{
  if(Mock.Security_isSecured_IgnoreBool)
    Mock.Security_isSecured_CallInstance = CMock_Guts_MemNext(Mock.Security_isSecured_CallInstance);
  Mock.Security_isSecured_IgnoreBool = (char)0;
}

void Security_isSecured_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Security_isSecured_CALL_INSTANCE));
  CMOCK_Security_isSecured_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_isSecured_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Security_isSecured_CallInstance = CMock_Guts_MemChain(Mock.Security_isSecured_CallInstance, cmock_guts_index);
  Mock.Security_isSecured_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Security_isSecured_AddCallback(CMOCK_Security_isSecured_CALLBACK Callback)
{
  Mock.Security_isSecured_IgnoreBool = (char)0;
  Mock.Security_isSecured_CallbackBool = (char)1;
  Mock.Security_isSecured_CallbackFunctionPointer = Callback;
}

void Security_isSecured_Stub(CMOCK_Security_isSecured_CALLBACK Callback)
{
  Mock.Security_isSecured_IgnoreBool = (char)0;
  Mock.Security_isSecured_CallbackBool = (char)0;
  Mock.Security_isSecured_CallbackFunctionPointer = Callback;
}

bool Security_decrypt(const uint8_t* mac, const uint8_t* nonce, const uint8_t* cipher_data, uint8_t* plain_data, const uint16_t data_length)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Security_decrypt_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Security_decrypt);
  cmock_call_instance = (CMOCK_Security_decrypt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Security_decrypt_CallInstance);
  Mock.Security_decrypt_CallInstance = CMock_Guts_MemNext(Mock.Security_decrypt_CallInstance);
  if (Mock.Security_decrypt_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.Security_decrypt_FinalReturn;
    Mock.Security_decrypt_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.Security_decrypt_CallbackBool &&
      Mock.Security_decrypt_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.Security_decrypt_CallbackFunctionPointer(mac, nonce, cipher_data, plain_data, data_length, Mock.Security_decrypt_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_mac)
  {
    UNITY_SET_DETAILS(CMockString_Security_decrypt,CMockString_mac);
    if (cmock_call_instance->Expected_mac == NULL)
      { UNITY_TEST_ASSERT_NULL(mac, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_mac, mac, cmock_call_instance->Expected_mac_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_nonce)
  {
    UNITY_SET_DETAILS(CMockString_Security_decrypt,CMockString_nonce);
    if (cmock_call_instance->Expected_nonce == NULL)
      { UNITY_TEST_ASSERT_NULL(nonce, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_nonce, nonce, cmock_call_instance->Expected_nonce_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_cipher_data)
  {
    UNITY_SET_DETAILS(CMockString_Security_decrypt,CMockString_cipher_data);
    if (cmock_call_instance->Expected_cipher_data == NULL)
      { UNITY_TEST_ASSERT_NULL(cipher_data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_cipher_data, cipher_data, cmock_call_instance->Expected_cipher_data_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_plain_data)
  {
    UNITY_SET_DETAILS(CMockString_Security_decrypt,CMockString_plain_data);
    if (cmock_call_instance->Expected_plain_data == NULL)
      { UNITY_TEST_ASSERT_NULL(plain_data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_plain_data, plain_data, cmock_call_instance->Expected_plain_data_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_data_length)
  {
    UNITY_SET_DETAILS(CMockString_Security_decrypt,CMockString_data_length);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_data_length, data_length, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.Security_decrypt_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.Security_decrypt_CallbackFunctionPointer(mac, nonce, cipher_data, plain_data, data_length, Mock.Security_decrypt_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_plain_data_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(plain_data, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)plain_data, (const void*)cmock_call_instance->ReturnThruPtr_plain_data_Val,
      cmock_call_instance->ReturnThruPtr_plain_data_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_Security_decrypt(CMOCK_Security_decrypt_CALL_INSTANCE* cmock_call_instance, const uint8_t* mac, int mac_Depth, const uint8_t* nonce, int nonce_Depth, const uint8_t* cipher_data, int cipher_data_Depth, uint8_t* plain_data, int plain_data_Depth, const uint16_t data_length);
void CMockExpectParameters_Security_decrypt(CMOCK_Security_decrypt_CALL_INSTANCE* cmock_call_instance, const uint8_t* mac, int mac_Depth, const uint8_t* nonce, int nonce_Depth, const uint8_t* cipher_data, int cipher_data_Depth, uint8_t* plain_data, int plain_data_Depth, const uint16_t data_length)
{
  cmock_call_instance->Expected_mac = mac;
  cmock_call_instance->Expected_mac_Depth = mac_Depth;
  cmock_call_instance->IgnoreArg_mac = 0;
  cmock_call_instance->Expected_nonce = nonce;
  cmock_call_instance->Expected_nonce_Depth = nonce_Depth;
  cmock_call_instance->IgnoreArg_nonce = 0;
  cmock_call_instance->Expected_cipher_data = cipher_data;
  cmock_call_instance->Expected_cipher_data_Depth = cipher_data_Depth;
  cmock_call_instance->IgnoreArg_cipher_data = 0;
  cmock_call_instance->Expected_plain_data = plain_data;
  cmock_call_instance->Expected_plain_data_Depth = plain_data_Depth;
  cmock_call_instance->IgnoreArg_plain_data = 0;
  cmock_call_instance->ReturnThruPtr_plain_data_Used = 0;
  cmock_call_instance->Expected_data_length = data_length;
  cmock_call_instance->IgnoreArg_data_length = 0;
}

void Security_decrypt_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Security_decrypt_CALL_INSTANCE));
  CMOCK_Security_decrypt_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_decrypt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Security_decrypt_CallInstance = CMock_Guts_MemChain(Mock.Security_decrypt_CallInstance, cmock_guts_index);
  Mock.Security_decrypt_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.Security_decrypt_IgnoreBool = (char)1;
}

void Security_decrypt_CMockStopIgnore(void)
{
  if(Mock.Security_decrypt_IgnoreBool)
    Mock.Security_decrypt_CallInstance = CMock_Guts_MemNext(Mock.Security_decrypt_CallInstance);
  Mock.Security_decrypt_IgnoreBool = (char)0;
}

void Security_decrypt_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Security_decrypt_CALL_INSTANCE));
  CMOCK_Security_decrypt_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_decrypt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Security_decrypt_CallInstance = CMock_Guts_MemChain(Mock.Security_decrypt_CallInstance, cmock_guts_index);
  Mock.Security_decrypt_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void Security_decrypt_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t* mac, const uint8_t* nonce, const uint8_t* cipher_data, uint8_t* plain_data, const uint16_t data_length, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Security_decrypt_CALL_INSTANCE));
  CMOCK_Security_decrypt_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_decrypt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Security_decrypt_CallInstance = CMock_Guts_MemChain(Mock.Security_decrypt_CallInstance, cmock_guts_index);
  Mock.Security_decrypt_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_Security_decrypt(cmock_call_instance, mac, 1, nonce, 1, cipher_data, 1, plain_data, 1, data_length);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Security_decrypt_AddCallback(CMOCK_Security_decrypt_CALLBACK Callback)
{
  Mock.Security_decrypt_IgnoreBool = (char)0;
  Mock.Security_decrypt_CallbackBool = (char)1;
  Mock.Security_decrypt_CallbackFunctionPointer = Callback;
}

void Security_decrypt_Stub(CMOCK_Security_decrypt_CALLBACK Callback)
{
  Mock.Security_decrypt_IgnoreBool = (char)0;
  Mock.Security_decrypt_CallbackBool = (char)0;
  Mock.Security_decrypt_CallbackFunctionPointer = Callback;
}

void Security_decrypt_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t* mac, int mac_Depth, const uint8_t* nonce, int nonce_Depth, const uint8_t* cipher_data, int cipher_data_Depth, uint8_t* plain_data, int plain_data_Depth, const uint16_t data_length, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Security_decrypt_CALL_INSTANCE));
  CMOCK_Security_decrypt_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_decrypt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Security_decrypt_CallInstance = CMock_Guts_MemChain(Mock.Security_decrypt_CallInstance, cmock_guts_index);
  Mock.Security_decrypt_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_Security_decrypt(cmock_call_instance, mac, mac_Depth, nonce, nonce_Depth, cipher_data, cipher_data_Depth, plain_data, plain_data_Depth, data_length);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Security_decrypt_CMockReturnMemThruPtr_plain_data(UNITY_LINE_TYPE cmock_line, uint8_t const* plain_data, size_t cmock_size)
{
  CMOCK_Security_decrypt_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_decrypt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Security_decrypt_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_plain_data_Used = 1;
  cmock_call_instance->ReturnThruPtr_plain_data_Val = plain_data;
  cmock_call_instance->ReturnThruPtr_plain_data_Size = cmock_size;
}

void Security_decrypt_CMockIgnoreArg_mac(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_Security_decrypt_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_decrypt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Security_decrypt_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mac = 1;
}

void Security_decrypt_CMockIgnoreArg_nonce(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_Security_decrypt_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_decrypt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Security_decrypt_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_nonce = 1;
}

void Security_decrypt_CMockIgnoreArg_cipher_data(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_Security_decrypt_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_decrypt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Security_decrypt_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_cipher_data = 1;
}

void Security_decrypt_CMockIgnoreArg_plain_data(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_Security_decrypt_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_decrypt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Security_decrypt_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_plain_data = 1;
}

void Security_decrypt_CMockIgnoreArg_data_length(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_Security_decrypt_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_decrypt_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Security_decrypt_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_data_length = 1;
}

void Security_wipeKeys(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Security_wipeKeys_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Security_wipeKeys);
  cmock_call_instance = (CMOCK_Security_wipeKeys_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Security_wipeKeys_CallInstance);
  Mock.Security_wipeKeys_CallInstance = CMock_Guts_MemNext(Mock.Security_wipeKeys_CallInstance);
  if (Mock.Security_wipeKeys_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.Security_wipeKeys_CallbackBool &&
      Mock.Security_wipeKeys_CallbackFunctionPointer != NULL)
  {
    Mock.Security_wipeKeys_CallbackFunctionPointer(Mock.Security_wipeKeys_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.Security_wipeKeys_CallbackFunctionPointer != NULL)
  {
    Mock.Security_wipeKeys_CallbackFunctionPointer(Mock.Security_wipeKeys_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void Security_wipeKeys_CMockIgnore(void)
{
  Mock.Security_wipeKeys_IgnoreBool = (char)1;
}

void Security_wipeKeys_CMockStopIgnore(void)
{
  Mock.Security_wipeKeys_IgnoreBool = (char)0;
}

void Security_wipeKeys_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Security_wipeKeys_CALL_INSTANCE));
  CMOCK_Security_wipeKeys_CALL_INSTANCE* cmock_call_instance = (CMOCK_Security_wipeKeys_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Security_wipeKeys_CallInstance = CMock_Guts_MemChain(Mock.Security_wipeKeys_CallInstance, cmock_guts_index);
  Mock.Security_wipeKeys_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void Security_wipeKeys_AddCallback(CMOCK_Security_wipeKeys_CALLBACK Callback)
{
  Mock.Security_wipeKeys_IgnoreBool = (char)0;
  Mock.Security_wipeKeys_CallbackBool = (char)1;
  Mock.Security_wipeKeys_CallbackFunctionPointer = Callback;
}

void Security_wipeKeys_Stub(CMOCK_Security_wipeKeys_CALLBACK Callback)
{
  Mock.Security_wipeKeys_IgnoreBool = (char)0;
  Mock.Security_wipeKeys_CallbackBool = (char)0;
  Mock.Security_wipeKeys_CallbackFunctionPointer = Callback;
}

