/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_security_adapter.h"

static const char* CMockString_SecurityAdapter_getRandomData = "SecurityAdapter_getRandomData";
static const char* CMockString_SecurityAdapter_init = "SecurityAdapter_init";
static const char* CMockString_data = "data";
static const char* CMockString_size = "size";

typedef struct _CMOCK_SecurityAdapter_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_SecurityAdapter_init_CALL_INSTANCE;

typedef struct _CMOCK_SecurityAdapter_getRandomData_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;
  uint8_t* Expected_data;
  uint32_t Expected_size;
  int Expected_data_Depth;
  char ReturnThruPtr_data_Used;
  uint8_t const* ReturnThruPtr_data_Val;
  size_t ReturnThruPtr_data_Size;
  char IgnoreArg_data;
  char IgnoreArg_size;

} CMOCK_SecurityAdapter_getRandomData_CALL_INSTANCE;

static struct mock_security_adapterInstance
{
  char SecurityAdapter_init_IgnoreBool;
  char SecurityAdapter_init_CallbackBool;
  CMOCK_SecurityAdapter_init_CALLBACK SecurityAdapter_init_CallbackFunctionPointer;
  int SecurityAdapter_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SecurityAdapter_init_CallInstance;
  char SecurityAdapter_getRandomData_IgnoreBool;
  bool SecurityAdapter_getRandomData_FinalReturn;
  char SecurityAdapter_getRandomData_CallbackBool;
  CMOCK_SecurityAdapter_getRandomData_CALLBACK SecurityAdapter_getRandomData_CallbackFunctionPointer;
  int SecurityAdapter_getRandomData_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SecurityAdapter_getRandomData_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_security_adapter_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.SecurityAdapter_init_CallInstance;
  if (Mock.SecurityAdapter_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SecurityAdapter_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SecurityAdapter_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.SecurityAdapter_getRandomData_CallInstance;
  if (Mock.SecurityAdapter_getRandomData_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SecurityAdapter_getRandomData);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SecurityAdapter_getRandomData_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_security_adapter_Init(void)
{
  mock_security_adapter_Destroy();
}

void mock_security_adapter_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void SecurityAdapter_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SecurityAdapter_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SecurityAdapter_init);
  cmock_call_instance = (CMOCK_SecurityAdapter_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SecurityAdapter_init_CallInstance);
  Mock.SecurityAdapter_init_CallInstance = CMock_Guts_MemNext(Mock.SecurityAdapter_init_CallInstance);
  if (Mock.SecurityAdapter_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.SecurityAdapter_init_CallbackBool &&
      Mock.SecurityAdapter_init_CallbackFunctionPointer != NULL)
  {
    Mock.SecurityAdapter_init_CallbackFunctionPointer(Mock.SecurityAdapter_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.SecurityAdapter_init_CallbackFunctionPointer != NULL)
  {
    Mock.SecurityAdapter_init_CallbackFunctionPointer(Mock.SecurityAdapter_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void SecurityAdapter_init_CMockIgnore(void)
{
  Mock.SecurityAdapter_init_IgnoreBool = (char)1;
}

void SecurityAdapter_init_CMockStopIgnore(void)
{
  Mock.SecurityAdapter_init_IgnoreBool = (char)0;
}

void SecurityAdapter_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SecurityAdapter_init_CALL_INSTANCE));
  CMOCK_SecurityAdapter_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_SecurityAdapter_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SecurityAdapter_init_CallInstance = CMock_Guts_MemChain(Mock.SecurityAdapter_init_CallInstance, cmock_guts_index);
  Mock.SecurityAdapter_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void SecurityAdapter_init_AddCallback(CMOCK_SecurityAdapter_init_CALLBACK Callback)
{
  Mock.SecurityAdapter_init_IgnoreBool = (char)0;
  Mock.SecurityAdapter_init_CallbackBool = (char)1;
  Mock.SecurityAdapter_init_CallbackFunctionPointer = Callback;
}

void SecurityAdapter_init_Stub(CMOCK_SecurityAdapter_init_CALLBACK Callback)
{
  Mock.SecurityAdapter_init_IgnoreBool = (char)0;
  Mock.SecurityAdapter_init_CallbackBool = (char)0;
  Mock.SecurityAdapter_init_CallbackFunctionPointer = Callback;
}

bool SecurityAdapter_getRandomData(uint8_t* data, uint32_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SecurityAdapter_getRandomData_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SecurityAdapter_getRandomData);
  cmock_call_instance = (CMOCK_SecurityAdapter_getRandomData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SecurityAdapter_getRandomData_CallInstance);
  Mock.SecurityAdapter_getRandomData_CallInstance = CMock_Guts_MemNext(Mock.SecurityAdapter_getRandomData_CallInstance);
  if (Mock.SecurityAdapter_getRandomData_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.SecurityAdapter_getRandomData_FinalReturn;
    Mock.SecurityAdapter_getRandomData_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.SecurityAdapter_getRandomData_CallbackBool &&
      Mock.SecurityAdapter_getRandomData_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.SecurityAdapter_getRandomData_CallbackFunctionPointer(data, size, Mock.SecurityAdapter_getRandomData_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_data)
  {
    UNITY_SET_DETAILS(CMockString_SecurityAdapter_getRandomData,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data, data, cmock_call_instance->Expected_data_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_size)
  {
    UNITY_SET_DETAILS(CMockString_SecurityAdapter_getRandomData,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_size, size, cmock_line, CMockStringMismatch);
  }
  if (Mock.SecurityAdapter_getRandomData_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.SecurityAdapter_getRandomData_CallbackFunctionPointer(data, size, Mock.SecurityAdapter_getRandomData_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_data_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(data, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)data, (const void*)cmock_call_instance->ReturnThruPtr_data_Val,
      cmock_call_instance->ReturnThruPtr_data_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SecurityAdapter_getRandomData(CMOCK_SecurityAdapter_getRandomData_CALL_INSTANCE* cmock_call_instance, uint8_t* data, int data_Depth, uint32_t size);
void CMockExpectParameters_SecurityAdapter_getRandomData(CMOCK_SecurityAdapter_getRandomData_CALL_INSTANCE* cmock_call_instance, uint8_t* data, int data_Depth, uint32_t size)
{
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->Expected_data_Depth = data_Depth;
  cmock_call_instance->IgnoreArg_data = 0;
  cmock_call_instance->ReturnThruPtr_data_Used = 0;
  cmock_call_instance->Expected_size = size;
  cmock_call_instance->IgnoreArg_size = 0;
}

void SecurityAdapter_getRandomData_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SecurityAdapter_getRandomData_CALL_INSTANCE));
  CMOCK_SecurityAdapter_getRandomData_CALL_INSTANCE* cmock_call_instance = (CMOCK_SecurityAdapter_getRandomData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SecurityAdapter_getRandomData_CallInstance = CMock_Guts_MemChain(Mock.SecurityAdapter_getRandomData_CallInstance, cmock_guts_index);
  Mock.SecurityAdapter_getRandomData_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.SecurityAdapter_getRandomData_IgnoreBool = (char)1;
}

void SecurityAdapter_getRandomData_CMockStopIgnore(void)
{
  if(Mock.SecurityAdapter_getRandomData_IgnoreBool)
    Mock.SecurityAdapter_getRandomData_CallInstance = CMock_Guts_MemNext(Mock.SecurityAdapter_getRandomData_CallInstance);
  Mock.SecurityAdapter_getRandomData_IgnoreBool = (char)0;
}

void SecurityAdapter_getRandomData_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* data, uint32_t size, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SecurityAdapter_getRandomData_CALL_INSTANCE));
  CMOCK_SecurityAdapter_getRandomData_CALL_INSTANCE* cmock_call_instance = (CMOCK_SecurityAdapter_getRandomData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SecurityAdapter_getRandomData_CallInstance = CMock_Guts_MemChain(Mock.SecurityAdapter_getRandomData_CallInstance, cmock_guts_index);
  Mock.SecurityAdapter_getRandomData_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_SecurityAdapter_getRandomData(cmock_call_instance, data, 1, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void SecurityAdapter_getRandomData_AddCallback(CMOCK_SecurityAdapter_getRandomData_CALLBACK Callback)
{
  Mock.SecurityAdapter_getRandomData_IgnoreBool = (char)0;
  Mock.SecurityAdapter_getRandomData_CallbackBool = (char)1;
  Mock.SecurityAdapter_getRandomData_CallbackFunctionPointer = Callback;
}

void SecurityAdapter_getRandomData_Stub(CMOCK_SecurityAdapter_getRandomData_CALLBACK Callback)
{
  Mock.SecurityAdapter_getRandomData_IgnoreBool = (char)0;
  Mock.SecurityAdapter_getRandomData_CallbackBool = (char)0;
  Mock.SecurityAdapter_getRandomData_CallbackFunctionPointer = Callback;
}

void SecurityAdapter_getRandomData_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* data, int data_Depth, uint32_t size, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SecurityAdapter_getRandomData_CALL_INSTANCE));
  CMOCK_SecurityAdapter_getRandomData_CALL_INSTANCE* cmock_call_instance = (CMOCK_SecurityAdapter_getRandomData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SecurityAdapter_getRandomData_CallInstance = CMock_Guts_MemChain(Mock.SecurityAdapter_getRandomData_CallInstance, cmock_guts_index);
  Mock.SecurityAdapter_getRandomData_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_SecurityAdapter_getRandomData(cmock_call_instance, data, data_Depth, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void SecurityAdapter_getRandomData_CMockReturnMemThruPtr_data(UNITY_LINE_TYPE cmock_line, uint8_t const* data, size_t cmock_size)
{
  CMOCK_SecurityAdapter_getRandomData_CALL_INSTANCE* cmock_call_instance = (CMOCK_SecurityAdapter_getRandomData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SecurityAdapter_getRandomData_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_data_Used = 1;
  cmock_call_instance->ReturnThruPtr_data_Val = data;
  cmock_call_instance->ReturnThruPtr_data_Size = cmock_size;
}

void SecurityAdapter_getRandomData_CMockIgnoreArg_data(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SecurityAdapter_getRandomData_CALL_INSTANCE* cmock_call_instance = (CMOCK_SecurityAdapter_getRandomData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SecurityAdapter_getRandomData_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_data = 1;
}

void SecurityAdapter_getRandomData_CMockIgnoreArg_size(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SecurityAdapter_getRandomData_CALL_INSTANCE* cmock_call_instance = (CMOCK_SecurityAdapter_getRandomData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SecurityAdapter_getRandomData_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_size = 1;
}

