/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_system_adapter.h"

static const char* CMockString_SystemAdapter_reset = "SystemAdapter_reset";

typedef struct _CMOCK_SystemAdapter_reset_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_SystemAdapter_reset_CALL_INSTANCE;

static struct mock_system_adapterInstance
{
  char SystemAdapter_reset_IgnoreBool;
  char SystemAdapter_reset_CallbackBool;
  CMOCK_SystemAdapter_reset_CALLBACK SystemAdapter_reset_CallbackFunctionPointer;
  int SystemAdapter_reset_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SystemAdapter_reset_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_system_adapter_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.SystemAdapter_reset_CallInstance;
  if (Mock.SystemAdapter_reset_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SystemAdapter_reset);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SystemAdapter_reset_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_system_adapter_Init(void)
{
  mock_system_adapter_Destroy();
}

void mock_system_adapter_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void SystemAdapter_reset(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SystemAdapter_reset_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SystemAdapter_reset);
  cmock_call_instance = (CMOCK_SystemAdapter_reset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SystemAdapter_reset_CallInstance);
  Mock.SystemAdapter_reset_CallInstance = CMock_Guts_MemNext(Mock.SystemAdapter_reset_CallInstance);
  if (Mock.SystemAdapter_reset_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.SystemAdapter_reset_CallbackBool &&
      Mock.SystemAdapter_reset_CallbackFunctionPointer != NULL)
  {
    Mock.SystemAdapter_reset_CallbackFunctionPointer(Mock.SystemAdapter_reset_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.SystemAdapter_reset_CallbackFunctionPointer != NULL)
  {
    Mock.SystemAdapter_reset_CallbackFunctionPointer(Mock.SystemAdapter_reset_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void SystemAdapter_reset_CMockIgnore(void)
{
  Mock.SystemAdapter_reset_IgnoreBool = (char)1;
}

void SystemAdapter_reset_CMockStopIgnore(void)
{
  Mock.SystemAdapter_reset_IgnoreBool = (char)0;
}

void SystemAdapter_reset_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SystemAdapter_reset_CALL_INSTANCE));
  CMOCK_SystemAdapter_reset_CALL_INSTANCE* cmock_call_instance = (CMOCK_SystemAdapter_reset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SystemAdapter_reset_CallInstance = CMock_Guts_MemChain(Mock.SystemAdapter_reset_CallInstance, cmock_guts_index);
  Mock.SystemAdapter_reset_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void SystemAdapter_reset_AddCallback(CMOCK_SystemAdapter_reset_CALLBACK Callback)
{
  Mock.SystemAdapter_reset_IgnoreBool = (char)0;
  Mock.SystemAdapter_reset_CallbackBool = (char)1;
  Mock.SystemAdapter_reset_CallbackFunctionPointer = Callback;
}

void SystemAdapter_reset_Stub(CMOCK_SystemAdapter_reset_CALLBACK Callback)
{
  Mock.SystemAdapter_reset_IgnoreBool = (char)0;
  Mock.SystemAdapter_reset_CallbackBool = (char)0;
  Mock.SystemAdapter_reset_CallbackFunctionPointer = Callback;
}

