/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_system_clock_adapter.h"

static const char* CMockString_SystemClock_Config = "SystemClock_Config";

typedef struct _CMOCK_SystemClock_Config_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_SystemClock_Config_CALL_INSTANCE;

static struct mock_system_clock_adapterInstance
{
  char SystemClock_Config_IgnoreBool;
  char SystemClock_Config_CallbackBool;
  CMOCK_SystemClock_Config_CALLBACK SystemClock_Config_CallbackFunctionPointer;
  int SystemClock_Config_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SystemClock_Config_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_system_clock_adapter_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.SystemClock_Config_CallInstance;
  if (Mock.SystemClock_Config_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SystemClock_Config);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SystemClock_Config_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_system_clock_adapter_Init(void)
{
  mock_system_clock_adapter_Destroy();
}

void mock_system_clock_adapter_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void SystemClock_Config(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SystemClock_Config_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SystemClock_Config);
  cmock_call_instance = (CMOCK_SystemClock_Config_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SystemClock_Config_CallInstance);
  Mock.SystemClock_Config_CallInstance = CMock_Guts_MemNext(Mock.SystemClock_Config_CallInstance);
  if (Mock.SystemClock_Config_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.SystemClock_Config_CallbackBool &&
      Mock.SystemClock_Config_CallbackFunctionPointer != NULL)
  {
    Mock.SystemClock_Config_CallbackFunctionPointer(Mock.SystemClock_Config_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.SystemClock_Config_CallbackFunctionPointer != NULL)
  {
    Mock.SystemClock_Config_CallbackFunctionPointer(Mock.SystemClock_Config_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void SystemClock_Config_CMockIgnore(void)
{
  Mock.SystemClock_Config_IgnoreBool = (char)1;
}

void SystemClock_Config_CMockStopIgnore(void)
{
  Mock.SystemClock_Config_IgnoreBool = (char)0;
}

void SystemClock_Config_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SystemClock_Config_CALL_INSTANCE));
  CMOCK_SystemClock_Config_CALL_INSTANCE* cmock_call_instance = (CMOCK_SystemClock_Config_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SystemClock_Config_CallInstance = CMock_Guts_MemChain(Mock.SystemClock_Config_CallInstance, cmock_guts_index);
  Mock.SystemClock_Config_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void SystemClock_Config_AddCallback(CMOCK_SystemClock_Config_CALLBACK Callback)
{
  Mock.SystemClock_Config_IgnoreBool = (char)0;
  Mock.SystemClock_Config_CallbackBool = (char)1;
  Mock.SystemClock_Config_CallbackFunctionPointer = Callback;
}

void SystemClock_Config_Stub(CMOCK_SystemClock_Config_CALLBACK Callback)
{
  Mock.SystemClock_Config_IgnoreBool = (char)0;
  Mock.SystemClock_Config_CallbackBool = (char)0;
  Mock.SystemClock_Config_CallbackFunctionPointer = Callback;
}

