/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_communication.h"

static const char* CMockString_Communication_handler = "Communication_handler";
static const char* CMockString_Communication_init = "Communication_init";
static const char* CMockString_Communication_mainLoop = "Communication_mainLoop";
static const char* CMockString_buf = "buf";
static const char* CMockString_length = "length";
static const char* CMockString_timeout = "timeout";

typedef struct _CMOCK_Communication_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_Communication_init_CALL_INSTANCE;

typedef struct _CMOCK_Communication_handler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;
  uint8_t* Expected_buf;
  uint32_t Expected_length;
  int Expected_buf_Depth;
  char ReturnThruPtr_buf_Used;
  uint8_t const* ReturnThruPtr_buf_Val;
  size_t ReturnThruPtr_buf_Size;
  char IgnoreArg_buf;
  char IgnoreArg_length;

} CMOCK_Communication_handler_CALL_INSTANCE;

typedef struct _CMOCK_Communication_mainLoop_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;
  uint32_t Expected_timeout;
  char IgnoreArg_timeout;

} CMOCK_Communication_mainLoop_CALL_INSTANCE;

static struct mock_communicationInstance
{
  char Communication_init_IgnoreBool;
  char Communication_init_CallbackBool;
  CMOCK_Communication_init_CALLBACK Communication_init_CallbackFunctionPointer;
  int Communication_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Communication_init_CallInstance;
  char Communication_handler_IgnoreBool;
  bool Communication_handler_FinalReturn;
  char Communication_handler_CallbackBool;
  CMOCK_Communication_handler_CALLBACK Communication_handler_CallbackFunctionPointer;
  int Communication_handler_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Communication_handler_CallInstance;
  char Communication_mainLoop_IgnoreBool;
  bool Communication_mainLoop_FinalReturn;
  char Communication_mainLoop_CallbackBool;
  CMOCK_Communication_mainLoop_CALLBACK Communication_mainLoop_CallbackFunctionPointer;
  int Communication_mainLoop_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Communication_mainLoop_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_communication_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.Communication_init_CallInstance;
  if (Mock.Communication_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Communication_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Communication_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Communication_handler_CallInstance;
  if (Mock.Communication_handler_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Communication_handler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Communication_handler_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Communication_mainLoop_CallInstance;
  if (Mock.Communication_mainLoop_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Communication_mainLoop);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Communication_mainLoop_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_communication_Init(void)
{
  mock_communication_Destroy();
}

void mock_communication_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void Communication_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Communication_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Communication_init);
  cmock_call_instance = (CMOCK_Communication_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Communication_init_CallInstance);
  Mock.Communication_init_CallInstance = CMock_Guts_MemNext(Mock.Communication_init_CallInstance);
  if (Mock.Communication_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.Communication_init_CallbackBool &&
      Mock.Communication_init_CallbackFunctionPointer != NULL)
  {
    Mock.Communication_init_CallbackFunctionPointer(Mock.Communication_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.Communication_init_CallbackFunctionPointer != NULL)
  {
    Mock.Communication_init_CallbackFunctionPointer(Mock.Communication_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void Communication_init_CMockIgnore(void)
{
  Mock.Communication_init_IgnoreBool = (char)1;
}

void Communication_init_CMockStopIgnore(void)
{
  Mock.Communication_init_IgnoreBool = (char)0;
}

void Communication_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Communication_init_CALL_INSTANCE));
  CMOCK_Communication_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_Communication_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Communication_init_CallInstance = CMock_Guts_MemChain(Mock.Communication_init_CallInstance, cmock_guts_index);
  Mock.Communication_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void Communication_init_AddCallback(CMOCK_Communication_init_CALLBACK Callback)
{
  Mock.Communication_init_IgnoreBool = (char)0;
  Mock.Communication_init_CallbackBool = (char)1;
  Mock.Communication_init_CallbackFunctionPointer = Callback;
}

void Communication_init_Stub(CMOCK_Communication_init_CALLBACK Callback)
{
  Mock.Communication_init_IgnoreBool = (char)0;
  Mock.Communication_init_CallbackBool = (char)0;
  Mock.Communication_init_CallbackFunctionPointer = Callback;
}

bool Communication_handler(uint8_t* buf, uint32_t length)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Communication_handler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Communication_handler);
  cmock_call_instance = (CMOCK_Communication_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Communication_handler_CallInstance);
  Mock.Communication_handler_CallInstance = CMock_Guts_MemNext(Mock.Communication_handler_CallInstance);
  if (Mock.Communication_handler_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.Communication_handler_FinalReturn;
    Mock.Communication_handler_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.Communication_handler_CallbackBool &&
      Mock.Communication_handler_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.Communication_handler_CallbackFunctionPointer(buf, length, Mock.Communication_handler_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_buf)
  {
    UNITY_SET_DETAILS(CMockString_Communication_handler,CMockString_buf);
    if (cmock_call_instance->Expected_buf == NULL)
      { UNITY_TEST_ASSERT_NULL(buf, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_buf, buf, cmock_call_instance->Expected_buf_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_length)
  {
    UNITY_SET_DETAILS(CMockString_Communication_handler,CMockString_length);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_length, length, cmock_line, CMockStringMismatch);
  }
  if (Mock.Communication_handler_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.Communication_handler_CallbackFunctionPointer(buf, length, Mock.Communication_handler_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_buf_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(buf, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)buf, (const void*)cmock_call_instance->ReturnThruPtr_buf_Val,
      cmock_call_instance->ReturnThruPtr_buf_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_Communication_handler(CMOCK_Communication_handler_CALL_INSTANCE* cmock_call_instance, uint8_t* buf, int buf_Depth, uint32_t length);
void CMockExpectParameters_Communication_handler(CMOCK_Communication_handler_CALL_INSTANCE* cmock_call_instance, uint8_t* buf, int buf_Depth, uint32_t length)
{
  cmock_call_instance->Expected_buf = buf;
  cmock_call_instance->Expected_buf_Depth = buf_Depth;
  cmock_call_instance->IgnoreArg_buf = 0;
  cmock_call_instance->ReturnThruPtr_buf_Used = 0;
  cmock_call_instance->Expected_length = length;
  cmock_call_instance->IgnoreArg_length = 0;
}

void Communication_handler_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Communication_handler_CALL_INSTANCE));
  CMOCK_Communication_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_Communication_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Communication_handler_CallInstance = CMock_Guts_MemChain(Mock.Communication_handler_CallInstance, cmock_guts_index);
  Mock.Communication_handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.Communication_handler_IgnoreBool = (char)1;
}

void Communication_handler_CMockStopIgnore(void)
{
  if(Mock.Communication_handler_IgnoreBool)
    Mock.Communication_handler_CallInstance = CMock_Guts_MemNext(Mock.Communication_handler_CallInstance);
  Mock.Communication_handler_IgnoreBool = (char)0;
}

void Communication_handler_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* buf, uint32_t length, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Communication_handler_CALL_INSTANCE));
  CMOCK_Communication_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_Communication_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Communication_handler_CallInstance = CMock_Guts_MemChain(Mock.Communication_handler_CallInstance, cmock_guts_index);
  Mock.Communication_handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_Communication_handler(cmock_call_instance, buf, 1, length);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Communication_handler_AddCallback(CMOCK_Communication_handler_CALLBACK Callback)
{
  Mock.Communication_handler_IgnoreBool = (char)0;
  Mock.Communication_handler_CallbackBool = (char)1;
  Mock.Communication_handler_CallbackFunctionPointer = Callback;
}

void Communication_handler_Stub(CMOCK_Communication_handler_CALLBACK Callback)
{
  Mock.Communication_handler_IgnoreBool = (char)0;
  Mock.Communication_handler_CallbackBool = (char)0;
  Mock.Communication_handler_CallbackFunctionPointer = Callback;
}

void Communication_handler_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* buf, int buf_Depth, uint32_t length, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Communication_handler_CALL_INSTANCE));
  CMOCK_Communication_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_Communication_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Communication_handler_CallInstance = CMock_Guts_MemChain(Mock.Communication_handler_CallInstance, cmock_guts_index);
  Mock.Communication_handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_Communication_handler(cmock_call_instance, buf, buf_Depth, length);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Communication_handler_CMockReturnMemThruPtr_buf(UNITY_LINE_TYPE cmock_line, uint8_t const* buf, size_t cmock_size)
{
  CMOCK_Communication_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_Communication_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Communication_handler_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_buf_Used = 1;
  cmock_call_instance->ReturnThruPtr_buf_Val = buf;
  cmock_call_instance->ReturnThruPtr_buf_Size = cmock_size;
}

void Communication_handler_CMockIgnoreArg_buf(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_Communication_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_Communication_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Communication_handler_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_buf = 1;
}

void Communication_handler_CMockIgnoreArg_length(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_Communication_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_Communication_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Communication_handler_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_length = 1;
}

bool Communication_mainLoop(const uint32_t timeout)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Communication_mainLoop_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Communication_mainLoop);
  cmock_call_instance = (CMOCK_Communication_mainLoop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Communication_mainLoop_CallInstance);
  Mock.Communication_mainLoop_CallInstance = CMock_Guts_MemNext(Mock.Communication_mainLoop_CallInstance);
  if (Mock.Communication_mainLoop_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.Communication_mainLoop_FinalReturn;
    Mock.Communication_mainLoop_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.Communication_mainLoop_CallbackBool &&
      Mock.Communication_mainLoop_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.Communication_mainLoop_CallbackFunctionPointer(timeout, Mock.Communication_mainLoop_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_timeout)
  {
    UNITY_SET_DETAILS(CMockString_Communication_mainLoop,CMockString_timeout);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_timeout, timeout, cmock_line, CMockStringMismatch);
  }
  if (Mock.Communication_mainLoop_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.Communication_mainLoop_CallbackFunctionPointer(timeout, Mock.Communication_mainLoop_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_Communication_mainLoop(CMOCK_Communication_mainLoop_CALL_INSTANCE* cmock_call_instance, const uint32_t timeout);
void CMockExpectParameters_Communication_mainLoop(CMOCK_Communication_mainLoop_CALL_INSTANCE* cmock_call_instance, const uint32_t timeout)
{
  cmock_call_instance->Expected_timeout = timeout;
  cmock_call_instance->IgnoreArg_timeout = 0;
}

void Communication_mainLoop_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Communication_mainLoop_CALL_INSTANCE));
  CMOCK_Communication_mainLoop_CALL_INSTANCE* cmock_call_instance = (CMOCK_Communication_mainLoop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Communication_mainLoop_CallInstance = CMock_Guts_MemChain(Mock.Communication_mainLoop_CallInstance, cmock_guts_index);
  Mock.Communication_mainLoop_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.Communication_mainLoop_IgnoreBool = (char)1;
}

void Communication_mainLoop_CMockStopIgnore(void)
{
  if(Mock.Communication_mainLoop_IgnoreBool)
    Mock.Communication_mainLoop_CallInstance = CMock_Guts_MemNext(Mock.Communication_mainLoop_CallInstance);
  Mock.Communication_mainLoop_IgnoreBool = (char)0;
}

void Communication_mainLoop_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const uint32_t timeout, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Communication_mainLoop_CALL_INSTANCE));
  CMOCK_Communication_mainLoop_CALL_INSTANCE* cmock_call_instance = (CMOCK_Communication_mainLoop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Communication_mainLoop_CallInstance = CMock_Guts_MemChain(Mock.Communication_mainLoop_CallInstance, cmock_guts_index);
  Mock.Communication_mainLoop_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_Communication_mainLoop(cmock_call_instance, timeout);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Communication_mainLoop_AddCallback(CMOCK_Communication_mainLoop_CALLBACK Callback)
{
  Mock.Communication_mainLoop_IgnoreBool = (char)0;
  Mock.Communication_mainLoop_CallbackBool = (char)1;
  Mock.Communication_mainLoop_CallbackFunctionPointer = Callback;
}

void Communication_mainLoop_Stub(CMOCK_Communication_mainLoop_CALLBACK Callback)
{
  Mock.Communication_mainLoop_IgnoreBool = (char)0;
  Mock.Communication_mainLoop_CallbackBool = (char)0;
  Mock.Communication_mainLoop_CallbackFunctionPointer = Callback;
}

void Communication_mainLoop_CMockIgnoreArg_timeout(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_Communication_mainLoop_CALL_INSTANCE* cmock_call_instance = (CMOCK_Communication_mainLoop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Communication_mainLoop_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_timeout = 1;
}

