/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_binary_update.h"

static const char* CMockString_BinaryUpdate_checkSkipLoopFlag = "BinaryUpdate_checkSkipLoopFlag";
static const char* CMockString_BinaryUpdate_disableLoopFlag = "BinaryUpdate_disableLoopFlag";
static const char* CMockString_BinaryUpdate_erase = "BinaryUpdate_erase";
static const char* CMockString_BinaryUpdate_finish = "BinaryUpdate_finish";
static const char* CMockString_BinaryUpdate_getJumpAddress = "BinaryUpdate_getJumpAddress";
static const char* CMockString_BinaryUpdate_handleBootInfo = "BinaryUpdate_handleBootInfo";
static const char* CMockString_BinaryUpdate_handleDetectedBinary = "BinaryUpdate_handleDetectedBinary";
static const char* CMockString_BinaryUpdate_resetJumpAddress = "BinaryUpdate_resetJumpAddress";
static const char* CMockString_BinaryUpdate_write = "BinaryUpdate_write";
static const char* CMockString_detected_binary = "detected_binary";
static const char* CMockString_firmware_size = "firmware_size";
static const char* CMockString_packet_length = "packet_length";
static const char* CMockString_write_buffer = "write_buffer";

typedef struct _CMOCK_BinaryUpdate_handleDetectedBinary_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;
  signatureType_E Expected_detected_binary;
  char IgnoreArg_detected_binary;

} CMOCK_BinaryUpdate_handleDetectedBinary_CALL_INSTANCE;

typedef struct _CMOCK_BinaryUpdate_handleBootInfo_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_BinaryUpdate_handleBootInfo_CALL_INSTANCE;

typedef struct _CMOCK_BinaryUpdate_getJumpAddress_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;

} CMOCK_BinaryUpdate_getJumpAddress_CALL_INSTANCE;

typedef struct _CMOCK_BinaryUpdate_resetJumpAddress_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_BinaryUpdate_resetJumpAddress_CALL_INSTANCE;

typedef struct _CMOCK_BinaryUpdate_checkSkipLoopFlag_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;

} CMOCK_BinaryUpdate_checkSkipLoopFlag_CALL_INSTANCE;

typedef struct _CMOCK_BinaryUpdate_disableLoopFlag_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_BinaryUpdate_disableLoopFlag_CALL_INSTANCE;

typedef struct _CMOCK_BinaryUpdate_erase_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;
  uint32_t Expected_firmware_size;
  char IgnoreArg_firmware_size;

} CMOCK_BinaryUpdate_erase_CALL_INSTANCE;

typedef struct _CMOCK_BinaryUpdate_write_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;
  uint8_t* Expected_write_buffer;
  uint32_t Expected_packet_length;
  int Expected_write_buffer_Depth;
  char ReturnThruPtr_write_buffer_Used;
  uint8_t const* ReturnThruPtr_write_buffer_Val;
  size_t ReturnThruPtr_write_buffer_Size;
  char IgnoreArg_write_buffer;
  char IgnoreArg_packet_length;

} CMOCK_BinaryUpdate_write_CALL_INSTANCE;

typedef struct _CMOCK_BinaryUpdate_finish_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;

} CMOCK_BinaryUpdate_finish_CALL_INSTANCE;

static struct mock_binary_updateInstance
{
  char BinaryUpdate_handleDetectedBinary_IgnoreBool;
  bool BinaryUpdate_handleDetectedBinary_FinalReturn;
  char BinaryUpdate_handleDetectedBinary_CallbackBool;
  CMOCK_BinaryUpdate_handleDetectedBinary_CALLBACK BinaryUpdate_handleDetectedBinary_CallbackFunctionPointer;
  int BinaryUpdate_handleDetectedBinary_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE BinaryUpdate_handleDetectedBinary_CallInstance;
  char BinaryUpdate_handleBootInfo_IgnoreBool;
  char BinaryUpdate_handleBootInfo_CallbackBool;
  CMOCK_BinaryUpdate_handleBootInfo_CALLBACK BinaryUpdate_handleBootInfo_CallbackFunctionPointer;
  int BinaryUpdate_handleBootInfo_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE BinaryUpdate_handleBootInfo_CallInstance;
  char BinaryUpdate_getJumpAddress_IgnoreBool;
  uint32_t BinaryUpdate_getJumpAddress_FinalReturn;
  char BinaryUpdate_getJumpAddress_CallbackBool;
  CMOCK_BinaryUpdate_getJumpAddress_CALLBACK BinaryUpdate_getJumpAddress_CallbackFunctionPointer;
  int BinaryUpdate_getJumpAddress_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE BinaryUpdate_getJumpAddress_CallInstance;
  char BinaryUpdate_resetJumpAddress_IgnoreBool;
  char BinaryUpdate_resetJumpAddress_CallbackBool;
  CMOCK_BinaryUpdate_resetJumpAddress_CALLBACK BinaryUpdate_resetJumpAddress_CallbackFunctionPointer;
  int BinaryUpdate_resetJumpAddress_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE BinaryUpdate_resetJumpAddress_CallInstance;
  char BinaryUpdate_checkSkipLoopFlag_IgnoreBool;
  bool BinaryUpdate_checkSkipLoopFlag_FinalReturn;
  char BinaryUpdate_checkSkipLoopFlag_CallbackBool;
  CMOCK_BinaryUpdate_checkSkipLoopFlag_CALLBACK BinaryUpdate_checkSkipLoopFlag_CallbackFunctionPointer;
  int BinaryUpdate_checkSkipLoopFlag_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE BinaryUpdate_checkSkipLoopFlag_CallInstance;
  char BinaryUpdate_disableLoopFlag_IgnoreBool;
  char BinaryUpdate_disableLoopFlag_CallbackBool;
  CMOCK_BinaryUpdate_disableLoopFlag_CALLBACK BinaryUpdate_disableLoopFlag_CallbackFunctionPointer;
  int BinaryUpdate_disableLoopFlag_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE BinaryUpdate_disableLoopFlag_CallInstance;
  char BinaryUpdate_erase_IgnoreBool;
  bool BinaryUpdate_erase_FinalReturn;
  char BinaryUpdate_erase_CallbackBool;
  CMOCK_BinaryUpdate_erase_CALLBACK BinaryUpdate_erase_CallbackFunctionPointer;
  int BinaryUpdate_erase_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE BinaryUpdate_erase_CallInstance;
  char BinaryUpdate_write_IgnoreBool;
  bool BinaryUpdate_write_FinalReturn;
  char BinaryUpdate_write_CallbackBool;
  CMOCK_BinaryUpdate_write_CALLBACK BinaryUpdate_write_CallbackFunctionPointer;
  int BinaryUpdate_write_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE BinaryUpdate_write_CallInstance;
  char BinaryUpdate_finish_IgnoreBool;
  bool BinaryUpdate_finish_FinalReturn;
  char BinaryUpdate_finish_CallbackBool;
  CMOCK_BinaryUpdate_finish_CALLBACK BinaryUpdate_finish_CallbackFunctionPointer;
  int BinaryUpdate_finish_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE BinaryUpdate_finish_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_binary_update_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.BinaryUpdate_handleDetectedBinary_CallInstance;
  if (Mock.BinaryUpdate_handleDetectedBinary_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_BinaryUpdate_handleDetectedBinary);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.BinaryUpdate_handleDetectedBinary_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.BinaryUpdate_handleBootInfo_CallInstance;
  if (Mock.BinaryUpdate_handleBootInfo_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_BinaryUpdate_handleBootInfo);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.BinaryUpdate_handleBootInfo_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.BinaryUpdate_getJumpAddress_CallInstance;
  if (Mock.BinaryUpdate_getJumpAddress_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_BinaryUpdate_getJumpAddress);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.BinaryUpdate_getJumpAddress_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.BinaryUpdate_resetJumpAddress_CallInstance;
  if (Mock.BinaryUpdate_resetJumpAddress_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_BinaryUpdate_resetJumpAddress);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.BinaryUpdate_resetJumpAddress_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.BinaryUpdate_checkSkipLoopFlag_CallInstance;
  if (Mock.BinaryUpdate_checkSkipLoopFlag_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_BinaryUpdate_checkSkipLoopFlag);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.BinaryUpdate_checkSkipLoopFlag_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.BinaryUpdate_disableLoopFlag_CallInstance;
  if (Mock.BinaryUpdate_disableLoopFlag_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_BinaryUpdate_disableLoopFlag);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.BinaryUpdate_disableLoopFlag_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.BinaryUpdate_erase_CallInstance;
  if (Mock.BinaryUpdate_erase_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_BinaryUpdate_erase);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.BinaryUpdate_erase_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.BinaryUpdate_write_CallInstance;
  if (Mock.BinaryUpdate_write_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_BinaryUpdate_write);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.BinaryUpdate_write_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.BinaryUpdate_finish_CallInstance;
  if (Mock.BinaryUpdate_finish_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_BinaryUpdate_finish);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.BinaryUpdate_finish_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_binary_update_Init(void)
{
  mock_binary_update_Destroy();
}

void mock_binary_update_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

bool BinaryUpdate_handleDetectedBinary(signatureType_E detected_binary)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_BinaryUpdate_handleDetectedBinary_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_BinaryUpdate_handleDetectedBinary);
  cmock_call_instance = (CMOCK_BinaryUpdate_handleDetectedBinary_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.BinaryUpdate_handleDetectedBinary_CallInstance);
  Mock.BinaryUpdate_handleDetectedBinary_CallInstance = CMock_Guts_MemNext(Mock.BinaryUpdate_handleDetectedBinary_CallInstance);
  if (Mock.BinaryUpdate_handleDetectedBinary_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.BinaryUpdate_handleDetectedBinary_FinalReturn;
    Mock.BinaryUpdate_handleDetectedBinary_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.BinaryUpdate_handleDetectedBinary_CallbackBool &&
      Mock.BinaryUpdate_handleDetectedBinary_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.BinaryUpdate_handleDetectedBinary_CallbackFunctionPointer(detected_binary, Mock.BinaryUpdate_handleDetectedBinary_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_detected_binary)
  {
    UNITY_SET_DETAILS(CMockString_BinaryUpdate_handleDetectedBinary,CMockString_detected_binary);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_detected_binary), (void*)(&detected_binary), sizeof(signatureType_E), cmock_line, CMockStringMismatch);
  }
  if (Mock.BinaryUpdate_handleDetectedBinary_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.BinaryUpdate_handleDetectedBinary_CallbackFunctionPointer(detected_binary, Mock.BinaryUpdate_handleDetectedBinary_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_BinaryUpdate_handleDetectedBinary(CMOCK_BinaryUpdate_handleDetectedBinary_CALL_INSTANCE* cmock_call_instance, signatureType_E detected_binary);
void CMockExpectParameters_BinaryUpdate_handleDetectedBinary(CMOCK_BinaryUpdate_handleDetectedBinary_CALL_INSTANCE* cmock_call_instance, signatureType_E detected_binary)
{
  memcpy((void*)(&cmock_call_instance->Expected_detected_binary), (void*)(&detected_binary),
         sizeof(signatureType_E[sizeof(detected_binary) == sizeof(signatureType_E) ? 1 : -1])); /* add signatureType_E to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_detected_binary = 0;
}

void BinaryUpdate_handleDetectedBinary_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BinaryUpdate_handleDetectedBinary_CALL_INSTANCE));
  CMOCK_BinaryUpdate_handleDetectedBinary_CALL_INSTANCE* cmock_call_instance = (CMOCK_BinaryUpdate_handleDetectedBinary_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BinaryUpdate_handleDetectedBinary_CallInstance = CMock_Guts_MemChain(Mock.BinaryUpdate_handleDetectedBinary_CallInstance, cmock_guts_index);
  Mock.BinaryUpdate_handleDetectedBinary_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.BinaryUpdate_handleDetectedBinary_IgnoreBool = (char)1;
}

void BinaryUpdate_handleDetectedBinary_CMockStopIgnore(void)
{
  if(Mock.BinaryUpdate_handleDetectedBinary_IgnoreBool)
    Mock.BinaryUpdate_handleDetectedBinary_CallInstance = CMock_Guts_MemNext(Mock.BinaryUpdate_handleDetectedBinary_CallInstance);
  Mock.BinaryUpdate_handleDetectedBinary_IgnoreBool = (char)0;
}

void BinaryUpdate_handleDetectedBinary_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, signatureType_E detected_binary, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BinaryUpdate_handleDetectedBinary_CALL_INSTANCE));
  CMOCK_BinaryUpdate_handleDetectedBinary_CALL_INSTANCE* cmock_call_instance = (CMOCK_BinaryUpdate_handleDetectedBinary_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BinaryUpdate_handleDetectedBinary_CallInstance = CMock_Guts_MemChain(Mock.BinaryUpdate_handleDetectedBinary_CallInstance, cmock_guts_index);
  Mock.BinaryUpdate_handleDetectedBinary_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_BinaryUpdate_handleDetectedBinary(cmock_call_instance, detected_binary);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void BinaryUpdate_handleDetectedBinary_AddCallback(CMOCK_BinaryUpdate_handleDetectedBinary_CALLBACK Callback)
{
  Mock.BinaryUpdate_handleDetectedBinary_IgnoreBool = (char)0;
  Mock.BinaryUpdate_handleDetectedBinary_CallbackBool = (char)1;
  Mock.BinaryUpdate_handleDetectedBinary_CallbackFunctionPointer = Callback;
}

void BinaryUpdate_handleDetectedBinary_Stub(CMOCK_BinaryUpdate_handleDetectedBinary_CALLBACK Callback)
{
  Mock.BinaryUpdate_handleDetectedBinary_IgnoreBool = (char)0;
  Mock.BinaryUpdate_handleDetectedBinary_CallbackBool = (char)0;
  Mock.BinaryUpdate_handleDetectedBinary_CallbackFunctionPointer = Callback;
}

void BinaryUpdate_handleDetectedBinary_CMockIgnoreArg_detected_binary(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_BinaryUpdate_handleDetectedBinary_CALL_INSTANCE* cmock_call_instance = (CMOCK_BinaryUpdate_handleDetectedBinary_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.BinaryUpdate_handleDetectedBinary_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_detected_binary = 1;
}

void BinaryUpdate_handleBootInfo(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_BinaryUpdate_handleBootInfo_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_BinaryUpdate_handleBootInfo);
  cmock_call_instance = (CMOCK_BinaryUpdate_handleBootInfo_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.BinaryUpdate_handleBootInfo_CallInstance);
  Mock.BinaryUpdate_handleBootInfo_CallInstance = CMock_Guts_MemNext(Mock.BinaryUpdate_handleBootInfo_CallInstance);
  if (Mock.BinaryUpdate_handleBootInfo_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.BinaryUpdate_handleBootInfo_CallbackBool &&
      Mock.BinaryUpdate_handleBootInfo_CallbackFunctionPointer != NULL)
  {
    Mock.BinaryUpdate_handleBootInfo_CallbackFunctionPointer(Mock.BinaryUpdate_handleBootInfo_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.BinaryUpdate_handleBootInfo_CallbackFunctionPointer != NULL)
  {
    Mock.BinaryUpdate_handleBootInfo_CallbackFunctionPointer(Mock.BinaryUpdate_handleBootInfo_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void BinaryUpdate_handleBootInfo_CMockIgnore(void)
{
  Mock.BinaryUpdate_handleBootInfo_IgnoreBool = (char)1;
}

void BinaryUpdate_handleBootInfo_CMockStopIgnore(void)
{
  Mock.BinaryUpdate_handleBootInfo_IgnoreBool = (char)0;
}

void BinaryUpdate_handleBootInfo_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BinaryUpdate_handleBootInfo_CALL_INSTANCE));
  CMOCK_BinaryUpdate_handleBootInfo_CALL_INSTANCE* cmock_call_instance = (CMOCK_BinaryUpdate_handleBootInfo_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BinaryUpdate_handleBootInfo_CallInstance = CMock_Guts_MemChain(Mock.BinaryUpdate_handleBootInfo_CallInstance, cmock_guts_index);
  Mock.BinaryUpdate_handleBootInfo_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void BinaryUpdate_handleBootInfo_AddCallback(CMOCK_BinaryUpdate_handleBootInfo_CALLBACK Callback)
{
  Mock.BinaryUpdate_handleBootInfo_IgnoreBool = (char)0;
  Mock.BinaryUpdate_handleBootInfo_CallbackBool = (char)1;
  Mock.BinaryUpdate_handleBootInfo_CallbackFunctionPointer = Callback;
}

void BinaryUpdate_handleBootInfo_Stub(CMOCK_BinaryUpdate_handleBootInfo_CALLBACK Callback)
{
  Mock.BinaryUpdate_handleBootInfo_IgnoreBool = (char)0;
  Mock.BinaryUpdate_handleBootInfo_CallbackBool = (char)0;
  Mock.BinaryUpdate_handleBootInfo_CallbackFunctionPointer = Callback;
}

uint32_t BinaryUpdate_getJumpAddress(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_BinaryUpdate_getJumpAddress_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_BinaryUpdate_getJumpAddress);
  cmock_call_instance = (CMOCK_BinaryUpdate_getJumpAddress_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.BinaryUpdate_getJumpAddress_CallInstance);
  Mock.BinaryUpdate_getJumpAddress_CallInstance = CMock_Guts_MemNext(Mock.BinaryUpdate_getJumpAddress_CallInstance);
  if (Mock.BinaryUpdate_getJumpAddress_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.BinaryUpdate_getJumpAddress_FinalReturn;
    Mock.BinaryUpdate_getJumpAddress_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.BinaryUpdate_getJumpAddress_CallbackBool &&
      Mock.BinaryUpdate_getJumpAddress_CallbackFunctionPointer != NULL)
  {
    uint32_t cmock_cb_ret = Mock.BinaryUpdate_getJumpAddress_CallbackFunctionPointer(Mock.BinaryUpdate_getJumpAddress_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.BinaryUpdate_getJumpAddress_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.BinaryUpdate_getJumpAddress_CallbackFunctionPointer(Mock.BinaryUpdate_getJumpAddress_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void BinaryUpdate_getJumpAddress_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BinaryUpdate_getJumpAddress_CALL_INSTANCE));
  CMOCK_BinaryUpdate_getJumpAddress_CALL_INSTANCE* cmock_call_instance = (CMOCK_BinaryUpdate_getJumpAddress_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BinaryUpdate_getJumpAddress_CallInstance = CMock_Guts_MemChain(Mock.BinaryUpdate_getJumpAddress_CallInstance, cmock_guts_index);
  Mock.BinaryUpdate_getJumpAddress_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.BinaryUpdate_getJumpAddress_IgnoreBool = (char)1;
}

void BinaryUpdate_getJumpAddress_CMockStopIgnore(void)
{
  if(Mock.BinaryUpdate_getJumpAddress_IgnoreBool)
    Mock.BinaryUpdate_getJumpAddress_CallInstance = CMock_Guts_MemNext(Mock.BinaryUpdate_getJumpAddress_CallInstance);
  Mock.BinaryUpdate_getJumpAddress_IgnoreBool = (char)0;
}

void BinaryUpdate_getJumpAddress_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BinaryUpdate_getJumpAddress_CALL_INSTANCE));
  CMOCK_BinaryUpdate_getJumpAddress_CALL_INSTANCE* cmock_call_instance = (CMOCK_BinaryUpdate_getJumpAddress_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BinaryUpdate_getJumpAddress_CallInstance = CMock_Guts_MemChain(Mock.BinaryUpdate_getJumpAddress_CallInstance, cmock_guts_index);
  Mock.BinaryUpdate_getJumpAddress_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void BinaryUpdate_getJumpAddress_AddCallback(CMOCK_BinaryUpdate_getJumpAddress_CALLBACK Callback)
{
  Mock.BinaryUpdate_getJumpAddress_IgnoreBool = (char)0;
  Mock.BinaryUpdate_getJumpAddress_CallbackBool = (char)1;
  Mock.BinaryUpdate_getJumpAddress_CallbackFunctionPointer = Callback;
}

void BinaryUpdate_getJumpAddress_Stub(CMOCK_BinaryUpdate_getJumpAddress_CALLBACK Callback)
{
  Mock.BinaryUpdate_getJumpAddress_IgnoreBool = (char)0;
  Mock.BinaryUpdate_getJumpAddress_CallbackBool = (char)0;
  Mock.BinaryUpdate_getJumpAddress_CallbackFunctionPointer = Callback;
}

void BinaryUpdate_resetJumpAddress(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_BinaryUpdate_resetJumpAddress_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_BinaryUpdate_resetJumpAddress);
  cmock_call_instance = (CMOCK_BinaryUpdate_resetJumpAddress_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.BinaryUpdate_resetJumpAddress_CallInstance);
  Mock.BinaryUpdate_resetJumpAddress_CallInstance = CMock_Guts_MemNext(Mock.BinaryUpdate_resetJumpAddress_CallInstance);
  if (Mock.BinaryUpdate_resetJumpAddress_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.BinaryUpdate_resetJumpAddress_CallbackBool &&
      Mock.BinaryUpdate_resetJumpAddress_CallbackFunctionPointer != NULL)
  {
    Mock.BinaryUpdate_resetJumpAddress_CallbackFunctionPointer(Mock.BinaryUpdate_resetJumpAddress_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.BinaryUpdate_resetJumpAddress_CallbackFunctionPointer != NULL)
  {
    Mock.BinaryUpdate_resetJumpAddress_CallbackFunctionPointer(Mock.BinaryUpdate_resetJumpAddress_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void BinaryUpdate_resetJumpAddress_CMockIgnore(void)
{
  Mock.BinaryUpdate_resetJumpAddress_IgnoreBool = (char)1;
}

void BinaryUpdate_resetJumpAddress_CMockStopIgnore(void)
{
  Mock.BinaryUpdate_resetJumpAddress_IgnoreBool = (char)0;
}

void BinaryUpdate_resetJumpAddress_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BinaryUpdate_resetJumpAddress_CALL_INSTANCE));
  CMOCK_BinaryUpdate_resetJumpAddress_CALL_INSTANCE* cmock_call_instance = (CMOCK_BinaryUpdate_resetJumpAddress_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BinaryUpdate_resetJumpAddress_CallInstance = CMock_Guts_MemChain(Mock.BinaryUpdate_resetJumpAddress_CallInstance, cmock_guts_index);
  Mock.BinaryUpdate_resetJumpAddress_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void BinaryUpdate_resetJumpAddress_AddCallback(CMOCK_BinaryUpdate_resetJumpAddress_CALLBACK Callback)
{
  Mock.BinaryUpdate_resetJumpAddress_IgnoreBool = (char)0;
  Mock.BinaryUpdate_resetJumpAddress_CallbackBool = (char)1;
  Mock.BinaryUpdate_resetJumpAddress_CallbackFunctionPointer = Callback;
}

void BinaryUpdate_resetJumpAddress_Stub(CMOCK_BinaryUpdate_resetJumpAddress_CALLBACK Callback)
{
  Mock.BinaryUpdate_resetJumpAddress_IgnoreBool = (char)0;
  Mock.BinaryUpdate_resetJumpAddress_CallbackBool = (char)0;
  Mock.BinaryUpdate_resetJumpAddress_CallbackFunctionPointer = Callback;
}

bool BinaryUpdate_checkSkipLoopFlag(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_BinaryUpdate_checkSkipLoopFlag_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_BinaryUpdate_checkSkipLoopFlag);
  cmock_call_instance = (CMOCK_BinaryUpdate_checkSkipLoopFlag_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.BinaryUpdate_checkSkipLoopFlag_CallInstance);
  Mock.BinaryUpdate_checkSkipLoopFlag_CallInstance = CMock_Guts_MemNext(Mock.BinaryUpdate_checkSkipLoopFlag_CallInstance);
  if (Mock.BinaryUpdate_checkSkipLoopFlag_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.BinaryUpdate_checkSkipLoopFlag_FinalReturn;
    Mock.BinaryUpdate_checkSkipLoopFlag_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.BinaryUpdate_checkSkipLoopFlag_CallbackBool &&
      Mock.BinaryUpdate_checkSkipLoopFlag_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.BinaryUpdate_checkSkipLoopFlag_CallbackFunctionPointer(Mock.BinaryUpdate_checkSkipLoopFlag_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.BinaryUpdate_checkSkipLoopFlag_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.BinaryUpdate_checkSkipLoopFlag_CallbackFunctionPointer(Mock.BinaryUpdate_checkSkipLoopFlag_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void BinaryUpdate_checkSkipLoopFlag_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BinaryUpdate_checkSkipLoopFlag_CALL_INSTANCE));
  CMOCK_BinaryUpdate_checkSkipLoopFlag_CALL_INSTANCE* cmock_call_instance = (CMOCK_BinaryUpdate_checkSkipLoopFlag_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BinaryUpdate_checkSkipLoopFlag_CallInstance = CMock_Guts_MemChain(Mock.BinaryUpdate_checkSkipLoopFlag_CallInstance, cmock_guts_index);
  Mock.BinaryUpdate_checkSkipLoopFlag_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.BinaryUpdate_checkSkipLoopFlag_IgnoreBool = (char)1;
}

void BinaryUpdate_checkSkipLoopFlag_CMockStopIgnore(void)
{
  if(Mock.BinaryUpdate_checkSkipLoopFlag_IgnoreBool)
    Mock.BinaryUpdate_checkSkipLoopFlag_CallInstance = CMock_Guts_MemNext(Mock.BinaryUpdate_checkSkipLoopFlag_CallInstance);
  Mock.BinaryUpdate_checkSkipLoopFlag_IgnoreBool = (char)0;
}

void BinaryUpdate_checkSkipLoopFlag_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BinaryUpdate_checkSkipLoopFlag_CALL_INSTANCE));
  CMOCK_BinaryUpdate_checkSkipLoopFlag_CALL_INSTANCE* cmock_call_instance = (CMOCK_BinaryUpdate_checkSkipLoopFlag_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BinaryUpdate_checkSkipLoopFlag_CallInstance = CMock_Guts_MemChain(Mock.BinaryUpdate_checkSkipLoopFlag_CallInstance, cmock_guts_index);
  Mock.BinaryUpdate_checkSkipLoopFlag_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void BinaryUpdate_checkSkipLoopFlag_AddCallback(CMOCK_BinaryUpdate_checkSkipLoopFlag_CALLBACK Callback)
{
  Mock.BinaryUpdate_checkSkipLoopFlag_IgnoreBool = (char)0;
  Mock.BinaryUpdate_checkSkipLoopFlag_CallbackBool = (char)1;
  Mock.BinaryUpdate_checkSkipLoopFlag_CallbackFunctionPointer = Callback;
}

void BinaryUpdate_checkSkipLoopFlag_Stub(CMOCK_BinaryUpdate_checkSkipLoopFlag_CALLBACK Callback)
{
  Mock.BinaryUpdate_checkSkipLoopFlag_IgnoreBool = (char)0;
  Mock.BinaryUpdate_checkSkipLoopFlag_CallbackBool = (char)0;
  Mock.BinaryUpdate_checkSkipLoopFlag_CallbackFunctionPointer = Callback;
}

void BinaryUpdate_disableLoopFlag(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_BinaryUpdate_disableLoopFlag_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_BinaryUpdate_disableLoopFlag);
  cmock_call_instance = (CMOCK_BinaryUpdate_disableLoopFlag_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.BinaryUpdate_disableLoopFlag_CallInstance);
  Mock.BinaryUpdate_disableLoopFlag_CallInstance = CMock_Guts_MemNext(Mock.BinaryUpdate_disableLoopFlag_CallInstance);
  if (Mock.BinaryUpdate_disableLoopFlag_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.BinaryUpdate_disableLoopFlag_CallbackBool &&
      Mock.BinaryUpdate_disableLoopFlag_CallbackFunctionPointer != NULL)
  {
    Mock.BinaryUpdate_disableLoopFlag_CallbackFunctionPointer(Mock.BinaryUpdate_disableLoopFlag_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.BinaryUpdate_disableLoopFlag_CallbackFunctionPointer != NULL)
  {
    Mock.BinaryUpdate_disableLoopFlag_CallbackFunctionPointer(Mock.BinaryUpdate_disableLoopFlag_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void BinaryUpdate_disableLoopFlag_CMockIgnore(void)
{
  Mock.BinaryUpdate_disableLoopFlag_IgnoreBool = (char)1;
}

void BinaryUpdate_disableLoopFlag_CMockStopIgnore(void)
{
  Mock.BinaryUpdate_disableLoopFlag_IgnoreBool = (char)0;
}

void BinaryUpdate_disableLoopFlag_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BinaryUpdate_disableLoopFlag_CALL_INSTANCE));
  CMOCK_BinaryUpdate_disableLoopFlag_CALL_INSTANCE* cmock_call_instance = (CMOCK_BinaryUpdate_disableLoopFlag_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BinaryUpdate_disableLoopFlag_CallInstance = CMock_Guts_MemChain(Mock.BinaryUpdate_disableLoopFlag_CallInstance, cmock_guts_index);
  Mock.BinaryUpdate_disableLoopFlag_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
}

void BinaryUpdate_disableLoopFlag_AddCallback(CMOCK_BinaryUpdate_disableLoopFlag_CALLBACK Callback)
{
  Mock.BinaryUpdate_disableLoopFlag_IgnoreBool = (char)0;
  Mock.BinaryUpdate_disableLoopFlag_CallbackBool = (char)1;
  Mock.BinaryUpdate_disableLoopFlag_CallbackFunctionPointer = Callback;
}

void BinaryUpdate_disableLoopFlag_Stub(CMOCK_BinaryUpdate_disableLoopFlag_CALLBACK Callback)
{
  Mock.BinaryUpdate_disableLoopFlag_IgnoreBool = (char)0;
  Mock.BinaryUpdate_disableLoopFlag_CallbackBool = (char)0;
  Mock.BinaryUpdate_disableLoopFlag_CallbackFunctionPointer = Callback;
}

bool BinaryUpdate_erase(uint32_t firmware_size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_BinaryUpdate_erase_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_BinaryUpdate_erase);
  cmock_call_instance = (CMOCK_BinaryUpdate_erase_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.BinaryUpdate_erase_CallInstance);
  Mock.BinaryUpdate_erase_CallInstance = CMock_Guts_MemNext(Mock.BinaryUpdate_erase_CallInstance);
  if (Mock.BinaryUpdate_erase_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.BinaryUpdate_erase_FinalReturn;
    Mock.BinaryUpdate_erase_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.BinaryUpdate_erase_CallbackBool &&
      Mock.BinaryUpdate_erase_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.BinaryUpdate_erase_CallbackFunctionPointer(firmware_size, Mock.BinaryUpdate_erase_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_firmware_size)
  {
    UNITY_SET_DETAILS(CMockString_BinaryUpdate_erase,CMockString_firmware_size);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_firmware_size, firmware_size, cmock_line, CMockStringMismatch);
  }
  if (Mock.BinaryUpdate_erase_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.BinaryUpdate_erase_CallbackFunctionPointer(firmware_size, Mock.BinaryUpdate_erase_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_BinaryUpdate_erase(CMOCK_BinaryUpdate_erase_CALL_INSTANCE* cmock_call_instance, uint32_t firmware_size);
void CMockExpectParameters_BinaryUpdate_erase(CMOCK_BinaryUpdate_erase_CALL_INSTANCE* cmock_call_instance, uint32_t firmware_size)
{
  cmock_call_instance->Expected_firmware_size = firmware_size;
  cmock_call_instance->IgnoreArg_firmware_size = 0;
}

void BinaryUpdate_erase_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BinaryUpdate_erase_CALL_INSTANCE));
  CMOCK_BinaryUpdate_erase_CALL_INSTANCE* cmock_call_instance = (CMOCK_BinaryUpdate_erase_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BinaryUpdate_erase_CallInstance = CMock_Guts_MemChain(Mock.BinaryUpdate_erase_CallInstance, cmock_guts_index);
  Mock.BinaryUpdate_erase_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.BinaryUpdate_erase_IgnoreBool = (char)1;
}

void BinaryUpdate_erase_CMockStopIgnore(void)
{
  if(Mock.BinaryUpdate_erase_IgnoreBool)
    Mock.BinaryUpdate_erase_CallInstance = CMock_Guts_MemNext(Mock.BinaryUpdate_erase_CallInstance);
  Mock.BinaryUpdate_erase_IgnoreBool = (char)0;
}

void BinaryUpdate_erase_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t firmware_size, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BinaryUpdate_erase_CALL_INSTANCE));
  CMOCK_BinaryUpdate_erase_CALL_INSTANCE* cmock_call_instance = (CMOCK_BinaryUpdate_erase_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BinaryUpdate_erase_CallInstance = CMock_Guts_MemChain(Mock.BinaryUpdate_erase_CallInstance, cmock_guts_index);
  Mock.BinaryUpdate_erase_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_BinaryUpdate_erase(cmock_call_instance, firmware_size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void BinaryUpdate_erase_AddCallback(CMOCK_BinaryUpdate_erase_CALLBACK Callback)
{
  Mock.BinaryUpdate_erase_IgnoreBool = (char)0;
  Mock.BinaryUpdate_erase_CallbackBool = (char)1;
  Mock.BinaryUpdate_erase_CallbackFunctionPointer = Callback;
}

void BinaryUpdate_erase_Stub(CMOCK_BinaryUpdate_erase_CALLBACK Callback)
{
  Mock.BinaryUpdate_erase_IgnoreBool = (char)0;
  Mock.BinaryUpdate_erase_CallbackBool = (char)0;
  Mock.BinaryUpdate_erase_CallbackFunctionPointer = Callback;
}

void BinaryUpdate_erase_CMockIgnoreArg_firmware_size(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_BinaryUpdate_erase_CALL_INSTANCE* cmock_call_instance = (CMOCK_BinaryUpdate_erase_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.BinaryUpdate_erase_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_firmware_size = 1;
}

bool BinaryUpdate_write(uint8_t* write_buffer, const uint32_t packet_length)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_BinaryUpdate_write_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_BinaryUpdate_write);
  cmock_call_instance = (CMOCK_BinaryUpdate_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.BinaryUpdate_write_CallInstance);
  Mock.BinaryUpdate_write_CallInstance = CMock_Guts_MemNext(Mock.BinaryUpdate_write_CallInstance);
  if (Mock.BinaryUpdate_write_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.BinaryUpdate_write_FinalReturn;
    Mock.BinaryUpdate_write_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.BinaryUpdate_write_CallbackBool &&
      Mock.BinaryUpdate_write_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.BinaryUpdate_write_CallbackFunctionPointer(write_buffer, packet_length, Mock.BinaryUpdate_write_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_write_buffer)
  {
    UNITY_SET_DETAILS(CMockString_BinaryUpdate_write,CMockString_write_buffer);
    if (cmock_call_instance->Expected_write_buffer == NULL)
      { UNITY_TEST_ASSERT_NULL(write_buffer, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_write_buffer, write_buffer, cmock_call_instance->Expected_write_buffer_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_packet_length)
  {
    UNITY_SET_DETAILS(CMockString_BinaryUpdate_write,CMockString_packet_length);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_packet_length, packet_length, cmock_line, CMockStringMismatch);
  }
  if (Mock.BinaryUpdate_write_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.BinaryUpdate_write_CallbackFunctionPointer(write_buffer, packet_length, Mock.BinaryUpdate_write_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_write_buffer_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(write_buffer, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)write_buffer, (const void*)cmock_call_instance->ReturnThruPtr_write_buffer_Val,
      cmock_call_instance->ReturnThruPtr_write_buffer_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_BinaryUpdate_write(CMOCK_BinaryUpdate_write_CALL_INSTANCE* cmock_call_instance, uint8_t* write_buffer, int write_buffer_Depth, const uint32_t packet_length);
void CMockExpectParameters_BinaryUpdate_write(CMOCK_BinaryUpdate_write_CALL_INSTANCE* cmock_call_instance, uint8_t* write_buffer, int write_buffer_Depth, const uint32_t packet_length)
{
  cmock_call_instance->Expected_write_buffer = write_buffer;
  cmock_call_instance->Expected_write_buffer_Depth = write_buffer_Depth;
  cmock_call_instance->IgnoreArg_write_buffer = 0;
  cmock_call_instance->ReturnThruPtr_write_buffer_Used = 0;
  cmock_call_instance->Expected_packet_length = packet_length;
  cmock_call_instance->IgnoreArg_packet_length = 0;
}

void BinaryUpdate_write_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BinaryUpdate_write_CALL_INSTANCE));
  CMOCK_BinaryUpdate_write_CALL_INSTANCE* cmock_call_instance = (CMOCK_BinaryUpdate_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BinaryUpdate_write_CallInstance = CMock_Guts_MemChain(Mock.BinaryUpdate_write_CallInstance, cmock_guts_index);
  Mock.BinaryUpdate_write_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.BinaryUpdate_write_IgnoreBool = (char)1;
}

void BinaryUpdate_write_CMockStopIgnore(void)
{
  if(Mock.BinaryUpdate_write_IgnoreBool)
    Mock.BinaryUpdate_write_CallInstance = CMock_Guts_MemNext(Mock.BinaryUpdate_write_CallInstance);
  Mock.BinaryUpdate_write_IgnoreBool = (char)0;
}

void BinaryUpdate_write_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* write_buffer, const uint32_t packet_length, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BinaryUpdate_write_CALL_INSTANCE));
  CMOCK_BinaryUpdate_write_CALL_INSTANCE* cmock_call_instance = (CMOCK_BinaryUpdate_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BinaryUpdate_write_CallInstance = CMock_Guts_MemChain(Mock.BinaryUpdate_write_CallInstance, cmock_guts_index);
  Mock.BinaryUpdate_write_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_BinaryUpdate_write(cmock_call_instance, write_buffer, 1, packet_length);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void BinaryUpdate_write_AddCallback(CMOCK_BinaryUpdate_write_CALLBACK Callback)
{
  Mock.BinaryUpdate_write_IgnoreBool = (char)0;
  Mock.BinaryUpdate_write_CallbackBool = (char)1;
  Mock.BinaryUpdate_write_CallbackFunctionPointer = Callback;
}

void BinaryUpdate_write_Stub(CMOCK_BinaryUpdate_write_CALLBACK Callback)
{
  Mock.BinaryUpdate_write_IgnoreBool = (char)0;
  Mock.BinaryUpdate_write_CallbackBool = (char)0;
  Mock.BinaryUpdate_write_CallbackFunctionPointer = Callback;
}

void BinaryUpdate_write_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* write_buffer, int write_buffer_Depth, const uint32_t packet_length, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BinaryUpdate_write_CALL_INSTANCE));
  CMOCK_BinaryUpdate_write_CALL_INSTANCE* cmock_call_instance = (CMOCK_BinaryUpdate_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BinaryUpdate_write_CallInstance = CMock_Guts_MemChain(Mock.BinaryUpdate_write_CallInstance, cmock_guts_index);
  Mock.BinaryUpdate_write_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_BinaryUpdate_write(cmock_call_instance, write_buffer, write_buffer_Depth, packet_length);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void BinaryUpdate_write_CMockReturnMemThruPtr_write_buffer(UNITY_LINE_TYPE cmock_line, uint8_t const* write_buffer, size_t cmock_size)
{
  CMOCK_BinaryUpdate_write_CALL_INSTANCE* cmock_call_instance = (CMOCK_BinaryUpdate_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.BinaryUpdate_write_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_write_buffer_Used = 1;
  cmock_call_instance->ReturnThruPtr_write_buffer_Val = write_buffer;
  cmock_call_instance->ReturnThruPtr_write_buffer_Size = cmock_size;
}

void BinaryUpdate_write_CMockIgnoreArg_write_buffer(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_BinaryUpdate_write_CALL_INSTANCE* cmock_call_instance = (CMOCK_BinaryUpdate_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.BinaryUpdate_write_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_write_buffer = 1;
}

void BinaryUpdate_write_CMockIgnoreArg_packet_length(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_BinaryUpdate_write_CALL_INSTANCE* cmock_call_instance = (CMOCK_BinaryUpdate_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.BinaryUpdate_write_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_packet_length = 1;
}

bool BinaryUpdate_finish(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_BinaryUpdate_finish_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_BinaryUpdate_finish);
  cmock_call_instance = (CMOCK_BinaryUpdate_finish_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.BinaryUpdate_finish_CallInstance);
  Mock.BinaryUpdate_finish_CallInstance = CMock_Guts_MemNext(Mock.BinaryUpdate_finish_CallInstance);
  if (Mock.BinaryUpdate_finish_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.BinaryUpdate_finish_FinalReturn;
    Mock.BinaryUpdate_finish_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.BinaryUpdate_finish_CallbackBool &&
      Mock.BinaryUpdate_finish_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.BinaryUpdate_finish_CallbackFunctionPointer(Mock.BinaryUpdate_finish_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.BinaryUpdate_finish_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.BinaryUpdate_finish_CallbackFunctionPointer(Mock.BinaryUpdate_finish_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void BinaryUpdate_finish_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BinaryUpdate_finish_CALL_INSTANCE));
  CMOCK_BinaryUpdate_finish_CALL_INSTANCE* cmock_call_instance = (CMOCK_BinaryUpdate_finish_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BinaryUpdate_finish_CallInstance = CMock_Guts_MemChain(Mock.BinaryUpdate_finish_CallInstance, cmock_guts_index);
  Mock.BinaryUpdate_finish_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.BinaryUpdate_finish_IgnoreBool = (char)1;
}

void BinaryUpdate_finish_CMockStopIgnore(void)
{
  if(Mock.BinaryUpdate_finish_IgnoreBool)
    Mock.BinaryUpdate_finish_CallInstance = CMock_Guts_MemNext(Mock.BinaryUpdate_finish_CallInstance);
  Mock.BinaryUpdate_finish_IgnoreBool = (char)0;
}

void BinaryUpdate_finish_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BinaryUpdate_finish_CALL_INSTANCE));
  CMOCK_BinaryUpdate_finish_CALL_INSTANCE* cmock_call_instance = (CMOCK_BinaryUpdate_finish_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BinaryUpdate_finish_CallInstance = CMock_Guts_MemChain(Mock.BinaryUpdate_finish_CallInstance, cmock_guts_index);
  Mock.BinaryUpdate_finish_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void BinaryUpdate_finish_AddCallback(CMOCK_BinaryUpdate_finish_CALLBACK Callback)
{
  Mock.BinaryUpdate_finish_IgnoreBool = (char)0;
  Mock.BinaryUpdate_finish_CallbackBool = (char)1;
  Mock.BinaryUpdate_finish_CallbackFunctionPointer = Callback;
}

void BinaryUpdate_finish_Stub(CMOCK_BinaryUpdate_finish_CALLBACK Callback)
{
  Mock.BinaryUpdate_finish_IgnoreBool = (char)0;
  Mock.BinaryUpdate_finish_CallbackBool = (char)0;
  Mock.BinaryUpdate_finish_CallbackFunctionPointer = Callback;
}

