/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_flash_adapter.h"

static const char* CMockString_FlashAdapter_blockErase = "FlashAdapter_blockErase";
static const char* CMockString_FlashAdapter_erase = "FlashAdapter_erase";
static const char* CMockString_FlashAdapter_finish = "FlashAdapter_finish";
static const char* CMockString_FlashAdapter_isFlashPCROPProtected = "FlashAdapter_isFlashPCROPProtected";
static const char* CMockString_FlashAdapter_isFlashRDPProtected = "FlashAdapter_isFlashRDPProtected";
static const char* CMockString_FlashAdapter_program = "FlashAdapter_program";
static const char* CMockString_FlashAdapter_readBytes = "FlashAdapter_readBytes";
static const char* CMockString_FlashAdapter_setPCROP = "FlashAdapter_setPCROP";
static const char* CMockString_FlashAdapter_setReadProtection = "FlashAdapter_setReadProtection";
static const char* CMockString_address = "address";
static const char* CMockString_buffer = "buffer";
static const char* CMockString_enable = "enable";
static const char* CMockString_firmware_size = "firmware_size";
static const char* CMockString_flash_address = "flash_address";
static const char* CMockString_length = "length";
static const char* CMockString_protect_address_end = "protect_address_end";
static const char* CMockString_protect_address_start = "protect_address_start";

typedef struct _CMOCK_FlashAdapter_erase_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;
  uint32_t Expected_firmware_size;
  uint32_t Expected_flash_address;
  char IgnoreArg_firmware_size;
  char IgnoreArg_flash_address;

} CMOCK_FlashAdapter_erase_CALL_INSTANCE;

typedef struct _CMOCK_FlashAdapter_blockErase_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;
  uint32_t Expected_address;
  char IgnoreArg_address;

} CMOCK_FlashAdapter_blockErase_CALL_INSTANCE;

typedef struct _CMOCK_FlashAdapter_program_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;
  uint32_t Expected_address;
  uint8_t* Expected_buffer;
  uint32_t Expected_length;
  int Expected_buffer_Depth;
  char ReturnThruPtr_buffer_Used;
  uint8_t const* ReturnThruPtr_buffer_Val;
  size_t ReturnThruPtr_buffer_Size;
  char IgnoreArg_address;
  char IgnoreArg_buffer;
  char IgnoreArg_length;

} CMOCK_FlashAdapter_program_CALL_INSTANCE;

typedef struct _CMOCK_FlashAdapter_readBytes_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;
  uint32_t Expected_address;
  uint8_t* Expected_buffer;
  uint32_t Expected_length;
  int Expected_buffer_Depth;
  char ReturnThruPtr_buffer_Used;
  uint8_t const* ReturnThruPtr_buffer_Val;
  size_t ReturnThruPtr_buffer_Size;
  char IgnoreArg_address;
  char IgnoreArg_buffer;
  char IgnoreArg_length;

} CMOCK_FlashAdapter_readBytes_CALL_INSTANCE;

typedef struct _CMOCK_FlashAdapter_finish_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;

} CMOCK_FlashAdapter_finish_CALL_INSTANCE;

typedef struct _CMOCK_FlashAdapter_isFlashRDPProtected_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;

} CMOCK_FlashAdapter_isFlashRDPProtected_CALL_INSTANCE;

typedef struct _CMOCK_FlashAdapter_isFlashPCROPProtected_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;

} CMOCK_FlashAdapter_isFlashPCROPProtected_CALL_INSTANCE;

typedef struct _CMOCK_FlashAdapter_setReadProtection_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;
  bool Expected_enable;
  char IgnoreArg_enable;

} CMOCK_FlashAdapter_setReadProtection_CALL_INSTANCE;

typedef struct _CMOCK_FlashAdapter_setPCROP_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;
  bool Expected_enable;
  uint32_t Expected_protect_address_start;
  uint32_t Expected_protect_address_end;
  char IgnoreArg_enable;
  char IgnoreArg_protect_address_start;
  char IgnoreArg_protect_address_end;

} CMOCK_FlashAdapter_setPCROP_CALL_INSTANCE;

static struct mock_flash_adapterInstance
{
  char FlashAdapter_erase_IgnoreBool;
  bool FlashAdapter_erase_FinalReturn;
  char FlashAdapter_erase_CallbackBool;
  CMOCK_FlashAdapter_erase_CALLBACK FlashAdapter_erase_CallbackFunctionPointer;
  int FlashAdapter_erase_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE FlashAdapter_erase_CallInstance;
  char FlashAdapter_blockErase_IgnoreBool;
  bool FlashAdapter_blockErase_FinalReturn;
  char FlashAdapter_blockErase_CallbackBool;
  CMOCK_FlashAdapter_blockErase_CALLBACK FlashAdapter_blockErase_CallbackFunctionPointer;
  int FlashAdapter_blockErase_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE FlashAdapter_blockErase_CallInstance;
  char FlashAdapter_program_IgnoreBool;
  bool FlashAdapter_program_FinalReturn;
  char FlashAdapter_program_CallbackBool;
  CMOCK_FlashAdapter_program_CALLBACK FlashAdapter_program_CallbackFunctionPointer;
  int FlashAdapter_program_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE FlashAdapter_program_CallInstance;
  char FlashAdapter_readBytes_IgnoreBool;
  bool FlashAdapter_readBytes_FinalReturn;
  char FlashAdapter_readBytes_CallbackBool;
  CMOCK_FlashAdapter_readBytes_CALLBACK FlashAdapter_readBytes_CallbackFunctionPointer;
  int FlashAdapter_readBytes_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE FlashAdapter_readBytes_CallInstance;
  char FlashAdapter_finish_IgnoreBool;
  bool FlashAdapter_finish_FinalReturn;
  char FlashAdapter_finish_CallbackBool;
  CMOCK_FlashAdapter_finish_CALLBACK FlashAdapter_finish_CallbackFunctionPointer;
  int FlashAdapter_finish_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE FlashAdapter_finish_CallInstance;
  char FlashAdapter_isFlashRDPProtected_IgnoreBool;
  bool FlashAdapter_isFlashRDPProtected_FinalReturn;
  char FlashAdapter_isFlashRDPProtected_CallbackBool;
  CMOCK_FlashAdapter_isFlashRDPProtected_CALLBACK FlashAdapter_isFlashRDPProtected_CallbackFunctionPointer;
  int FlashAdapter_isFlashRDPProtected_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE FlashAdapter_isFlashRDPProtected_CallInstance;
  char FlashAdapter_isFlashPCROPProtected_IgnoreBool;
  bool FlashAdapter_isFlashPCROPProtected_FinalReturn;
  char FlashAdapter_isFlashPCROPProtected_CallbackBool;
  CMOCK_FlashAdapter_isFlashPCROPProtected_CALLBACK FlashAdapter_isFlashPCROPProtected_CallbackFunctionPointer;
  int FlashAdapter_isFlashPCROPProtected_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE FlashAdapter_isFlashPCROPProtected_CallInstance;
  char FlashAdapter_setReadProtection_IgnoreBool;
  bool FlashAdapter_setReadProtection_FinalReturn;
  char FlashAdapter_setReadProtection_CallbackBool;
  CMOCK_FlashAdapter_setReadProtection_CALLBACK FlashAdapter_setReadProtection_CallbackFunctionPointer;
  int FlashAdapter_setReadProtection_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE FlashAdapter_setReadProtection_CallInstance;
  char FlashAdapter_setPCROP_IgnoreBool;
  bool FlashAdapter_setPCROP_FinalReturn;
  char FlashAdapter_setPCROP_CallbackBool;
  CMOCK_FlashAdapter_setPCROP_CALLBACK FlashAdapter_setPCROP_CallbackFunctionPointer;
  int FlashAdapter_setPCROP_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE FlashAdapter_setPCROP_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_flash_adapter_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.FlashAdapter_erase_CallInstance;
  if (Mock.FlashAdapter_erase_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FlashAdapter_erase);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.FlashAdapter_erase_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.FlashAdapter_blockErase_CallInstance;
  if (Mock.FlashAdapter_blockErase_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FlashAdapter_blockErase);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.FlashAdapter_blockErase_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.FlashAdapter_program_CallInstance;
  if (Mock.FlashAdapter_program_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FlashAdapter_program);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.FlashAdapter_program_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.FlashAdapter_readBytes_CallInstance;
  if (Mock.FlashAdapter_readBytes_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FlashAdapter_readBytes);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.FlashAdapter_readBytes_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.FlashAdapter_finish_CallInstance;
  if (Mock.FlashAdapter_finish_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FlashAdapter_finish);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.FlashAdapter_finish_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.FlashAdapter_isFlashRDPProtected_CallInstance;
  if (Mock.FlashAdapter_isFlashRDPProtected_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FlashAdapter_isFlashRDPProtected);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.FlashAdapter_isFlashRDPProtected_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.FlashAdapter_isFlashPCROPProtected_CallInstance;
  if (Mock.FlashAdapter_isFlashPCROPProtected_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FlashAdapter_isFlashPCROPProtected);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.FlashAdapter_isFlashPCROPProtected_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.FlashAdapter_setReadProtection_CallInstance;
  if (Mock.FlashAdapter_setReadProtection_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FlashAdapter_setReadProtection);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.FlashAdapter_setReadProtection_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.FlashAdapter_setPCROP_CallInstance;
  if (Mock.FlashAdapter_setPCROP_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FlashAdapter_setPCROP);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.FlashAdapter_setPCROP_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_flash_adapter_Init(void)
{
  mock_flash_adapter_Destroy();
}

void mock_flash_adapter_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

bool FlashAdapter_erase(uint32_t firmware_size, uint32_t flash_address)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FlashAdapter_erase_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FlashAdapter_erase);
  cmock_call_instance = (CMOCK_FlashAdapter_erase_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FlashAdapter_erase_CallInstance);
  Mock.FlashAdapter_erase_CallInstance = CMock_Guts_MemNext(Mock.FlashAdapter_erase_CallInstance);
  if (Mock.FlashAdapter_erase_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.FlashAdapter_erase_FinalReturn;
    Mock.FlashAdapter_erase_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.FlashAdapter_erase_CallbackBool &&
      Mock.FlashAdapter_erase_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.FlashAdapter_erase_CallbackFunctionPointer(firmware_size, flash_address, Mock.FlashAdapter_erase_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_firmware_size)
  {
    UNITY_SET_DETAILS(CMockString_FlashAdapter_erase,CMockString_firmware_size);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_firmware_size, firmware_size, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_flash_address)
  {
    UNITY_SET_DETAILS(CMockString_FlashAdapter_erase,CMockString_flash_address);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_flash_address, flash_address, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.FlashAdapter_erase_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.FlashAdapter_erase_CallbackFunctionPointer(firmware_size, flash_address, Mock.FlashAdapter_erase_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_FlashAdapter_erase(CMOCK_FlashAdapter_erase_CALL_INSTANCE* cmock_call_instance, uint32_t firmware_size, uint32_t flash_address);
void CMockExpectParameters_FlashAdapter_erase(CMOCK_FlashAdapter_erase_CALL_INSTANCE* cmock_call_instance, uint32_t firmware_size, uint32_t flash_address)
{
  cmock_call_instance->Expected_firmware_size = firmware_size;
  cmock_call_instance->IgnoreArg_firmware_size = 0;
  cmock_call_instance->Expected_flash_address = flash_address;
  cmock_call_instance->IgnoreArg_flash_address = 0;
}

void FlashAdapter_erase_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_erase_CALL_INSTANCE));
  CMOCK_FlashAdapter_erase_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_erase_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_erase_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_erase_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_erase_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.FlashAdapter_erase_IgnoreBool = (char)1;
}

void FlashAdapter_erase_CMockStopIgnore(void)
{
  if(Mock.FlashAdapter_erase_IgnoreBool)
    Mock.FlashAdapter_erase_CallInstance = CMock_Guts_MemNext(Mock.FlashAdapter_erase_CallInstance);
  Mock.FlashAdapter_erase_IgnoreBool = (char)0;
}

void FlashAdapter_erase_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_erase_CALL_INSTANCE));
  CMOCK_FlashAdapter_erase_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_erase_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_erase_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_erase_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_erase_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void FlashAdapter_erase_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t firmware_size, uint32_t flash_address, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_erase_CALL_INSTANCE));
  CMOCK_FlashAdapter_erase_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_erase_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_erase_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_erase_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_erase_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_FlashAdapter_erase(cmock_call_instance, firmware_size, flash_address);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void FlashAdapter_erase_AddCallback(CMOCK_FlashAdapter_erase_CALLBACK Callback)
{
  Mock.FlashAdapter_erase_IgnoreBool = (char)0;
  Mock.FlashAdapter_erase_CallbackBool = (char)1;
  Mock.FlashAdapter_erase_CallbackFunctionPointer = Callback;
}

void FlashAdapter_erase_Stub(CMOCK_FlashAdapter_erase_CALLBACK Callback)
{
  Mock.FlashAdapter_erase_IgnoreBool = (char)0;
  Mock.FlashAdapter_erase_CallbackBool = (char)0;
  Mock.FlashAdapter_erase_CallbackFunctionPointer = Callback;
}

void FlashAdapter_erase_CMockIgnoreArg_firmware_size(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_FlashAdapter_erase_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_erase_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.FlashAdapter_erase_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_firmware_size = 1;
}

void FlashAdapter_erase_CMockIgnoreArg_flash_address(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_FlashAdapter_erase_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_erase_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.FlashAdapter_erase_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_flash_address = 1;
}

bool FlashAdapter_blockErase(uint32_t address)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FlashAdapter_blockErase_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FlashAdapter_blockErase);
  cmock_call_instance = (CMOCK_FlashAdapter_blockErase_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FlashAdapter_blockErase_CallInstance);
  Mock.FlashAdapter_blockErase_CallInstance = CMock_Guts_MemNext(Mock.FlashAdapter_blockErase_CallInstance);
  if (Mock.FlashAdapter_blockErase_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.FlashAdapter_blockErase_FinalReturn;
    Mock.FlashAdapter_blockErase_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.FlashAdapter_blockErase_CallbackBool &&
      Mock.FlashAdapter_blockErase_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.FlashAdapter_blockErase_CallbackFunctionPointer(address, Mock.FlashAdapter_blockErase_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_address)
  {
    UNITY_SET_DETAILS(CMockString_FlashAdapter_blockErase,CMockString_address);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_address, address, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.FlashAdapter_blockErase_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.FlashAdapter_blockErase_CallbackFunctionPointer(address, Mock.FlashAdapter_blockErase_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_FlashAdapter_blockErase(CMOCK_FlashAdapter_blockErase_CALL_INSTANCE* cmock_call_instance, uint32_t address);
void CMockExpectParameters_FlashAdapter_blockErase(CMOCK_FlashAdapter_blockErase_CALL_INSTANCE* cmock_call_instance, uint32_t address)
{
  cmock_call_instance->Expected_address = address;
  cmock_call_instance->IgnoreArg_address = 0;
}

void FlashAdapter_blockErase_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_blockErase_CALL_INSTANCE));
  CMOCK_FlashAdapter_blockErase_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_blockErase_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_blockErase_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_blockErase_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_blockErase_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.FlashAdapter_blockErase_IgnoreBool = (char)1;
}

void FlashAdapter_blockErase_CMockStopIgnore(void)
{
  if(Mock.FlashAdapter_blockErase_IgnoreBool)
    Mock.FlashAdapter_blockErase_CallInstance = CMock_Guts_MemNext(Mock.FlashAdapter_blockErase_CallInstance);
  Mock.FlashAdapter_blockErase_IgnoreBool = (char)0;
}

void FlashAdapter_blockErase_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_blockErase_CALL_INSTANCE));
  CMOCK_FlashAdapter_blockErase_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_blockErase_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_blockErase_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_blockErase_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_blockErase_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void FlashAdapter_blockErase_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t address, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_blockErase_CALL_INSTANCE));
  CMOCK_FlashAdapter_blockErase_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_blockErase_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_blockErase_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_blockErase_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_blockErase_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_FlashAdapter_blockErase(cmock_call_instance, address);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void FlashAdapter_blockErase_AddCallback(CMOCK_FlashAdapter_blockErase_CALLBACK Callback)
{
  Mock.FlashAdapter_blockErase_IgnoreBool = (char)0;
  Mock.FlashAdapter_blockErase_CallbackBool = (char)1;
  Mock.FlashAdapter_blockErase_CallbackFunctionPointer = Callback;
}

void FlashAdapter_blockErase_Stub(CMOCK_FlashAdapter_blockErase_CALLBACK Callback)
{
  Mock.FlashAdapter_blockErase_IgnoreBool = (char)0;
  Mock.FlashAdapter_blockErase_CallbackBool = (char)0;
  Mock.FlashAdapter_blockErase_CallbackFunctionPointer = Callback;
}

void FlashAdapter_blockErase_CMockIgnoreArg_address(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_FlashAdapter_blockErase_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_blockErase_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.FlashAdapter_blockErase_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_address = 1;
}

bool FlashAdapter_program(uint32_t address, uint8_t* buffer, uint32_t length)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FlashAdapter_program_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FlashAdapter_program);
  cmock_call_instance = (CMOCK_FlashAdapter_program_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FlashAdapter_program_CallInstance);
  Mock.FlashAdapter_program_CallInstance = CMock_Guts_MemNext(Mock.FlashAdapter_program_CallInstance);
  if (Mock.FlashAdapter_program_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.FlashAdapter_program_FinalReturn;
    Mock.FlashAdapter_program_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.FlashAdapter_program_CallbackBool &&
      Mock.FlashAdapter_program_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.FlashAdapter_program_CallbackFunctionPointer(address, buffer, length, Mock.FlashAdapter_program_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_address)
  {
    UNITY_SET_DETAILS(CMockString_FlashAdapter_program,CMockString_address);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_address, address, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_buffer)
  {
    UNITY_SET_DETAILS(CMockString_FlashAdapter_program,CMockString_buffer);
    if (cmock_call_instance->Expected_buffer == NULL)
      { UNITY_TEST_ASSERT_NULL(buffer, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_buffer, buffer, cmock_call_instance->Expected_buffer_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_length)
  {
    UNITY_SET_DETAILS(CMockString_FlashAdapter_program,CMockString_length);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_length, length, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.FlashAdapter_program_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.FlashAdapter_program_CallbackFunctionPointer(address, buffer, length, Mock.FlashAdapter_program_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_buffer_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(buffer, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)buffer, (const void*)cmock_call_instance->ReturnThruPtr_buffer_Val,
      cmock_call_instance->ReturnThruPtr_buffer_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_FlashAdapter_program(CMOCK_FlashAdapter_program_CALL_INSTANCE* cmock_call_instance, uint32_t address, uint8_t* buffer, int buffer_Depth, uint32_t length);
void CMockExpectParameters_FlashAdapter_program(CMOCK_FlashAdapter_program_CALL_INSTANCE* cmock_call_instance, uint32_t address, uint8_t* buffer, int buffer_Depth, uint32_t length)
{
  cmock_call_instance->Expected_address = address;
  cmock_call_instance->IgnoreArg_address = 0;
  cmock_call_instance->Expected_buffer = buffer;
  cmock_call_instance->Expected_buffer_Depth = buffer_Depth;
  cmock_call_instance->IgnoreArg_buffer = 0;
  cmock_call_instance->ReturnThruPtr_buffer_Used = 0;
  cmock_call_instance->Expected_length = length;
  cmock_call_instance->IgnoreArg_length = 0;
}

void FlashAdapter_program_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_program_CALL_INSTANCE));
  CMOCK_FlashAdapter_program_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_program_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_program_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_program_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_program_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.FlashAdapter_program_IgnoreBool = (char)1;
}

void FlashAdapter_program_CMockStopIgnore(void)
{
  if(Mock.FlashAdapter_program_IgnoreBool)
    Mock.FlashAdapter_program_CallInstance = CMock_Guts_MemNext(Mock.FlashAdapter_program_CallInstance);
  Mock.FlashAdapter_program_IgnoreBool = (char)0;
}

void FlashAdapter_program_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_program_CALL_INSTANCE));
  CMOCK_FlashAdapter_program_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_program_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_program_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_program_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_program_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void FlashAdapter_program_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t address, uint8_t* buffer, uint32_t length, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_program_CALL_INSTANCE));
  CMOCK_FlashAdapter_program_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_program_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_program_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_program_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_program_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_FlashAdapter_program(cmock_call_instance, address, buffer, 1, length);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void FlashAdapter_program_AddCallback(CMOCK_FlashAdapter_program_CALLBACK Callback)
{
  Mock.FlashAdapter_program_IgnoreBool = (char)0;
  Mock.FlashAdapter_program_CallbackBool = (char)1;
  Mock.FlashAdapter_program_CallbackFunctionPointer = Callback;
}

void FlashAdapter_program_Stub(CMOCK_FlashAdapter_program_CALLBACK Callback)
{
  Mock.FlashAdapter_program_IgnoreBool = (char)0;
  Mock.FlashAdapter_program_CallbackBool = (char)0;
  Mock.FlashAdapter_program_CallbackFunctionPointer = Callback;
}

void FlashAdapter_program_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t address, uint8_t* buffer, int buffer_Depth, uint32_t length, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_program_CALL_INSTANCE));
  CMOCK_FlashAdapter_program_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_program_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_program_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_program_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_program_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_FlashAdapter_program(cmock_call_instance, address, buffer, buffer_Depth, length);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void FlashAdapter_program_CMockReturnMemThruPtr_buffer(UNITY_LINE_TYPE cmock_line, uint8_t const* buffer, size_t cmock_size)
{
  CMOCK_FlashAdapter_program_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_program_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.FlashAdapter_program_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_buffer_Used = 1;
  cmock_call_instance->ReturnThruPtr_buffer_Val = buffer;
  cmock_call_instance->ReturnThruPtr_buffer_Size = cmock_size;
}

void FlashAdapter_program_CMockIgnoreArg_address(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_FlashAdapter_program_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_program_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.FlashAdapter_program_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_address = 1;
}

void FlashAdapter_program_CMockIgnoreArg_buffer(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_FlashAdapter_program_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_program_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.FlashAdapter_program_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_buffer = 1;
}

void FlashAdapter_program_CMockIgnoreArg_length(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_FlashAdapter_program_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_program_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.FlashAdapter_program_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_length = 1;
}

bool FlashAdapter_readBytes(uint32_t address, uint8_t* buffer, uint32_t length)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FlashAdapter_readBytes_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FlashAdapter_readBytes);
  cmock_call_instance = (CMOCK_FlashAdapter_readBytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FlashAdapter_readBytes_CallInstance);
  Mock.FlashAdapter_readBytes_CallInstance = CMock_Guts_MemNext(Mock.FlashAdapter_readBytes_CallInstance);
  if (Mock.FlashAdapter_readBytes_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.FlashAdapter_readBytes_FinalReturn;
    Mock.FlashAdapter_readBytes_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.FlashAdapter_readBytes_CallbackBool &&
      Mock.FlashAdapter_readBytes_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.FlashAdapter_readBytes_CallbackFunctionPointer(address, buffer, length, Mock.FlashAdapter_readBytes_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_address)
  {
    UNITY_SET_DETAILS(CMockString_FlashAdapter_readBytes,CMockString_address);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_address, address, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_buffer)
  {
    UNITY_SET_DETAILS(CMockString_FlashAdapter_readBytes,CMockString_buffer);
    if (cmock_call_instance->Expected_buffer == NULL)
      { UNITY_TEST_ASSERT_NULL(buffer, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_buffer, buffer, cmock_call_instance->Expected_buffer_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_length)
  {
    UNITY_SET_DETAILS(CMockString_FlashAdapter_readBytes,CMockString_length);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_length, length, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.FlashAdapter_readBytes_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.FlashAdapter_readBytes_CallbackFunctionPointer(address, buffer, length, Mock.FlashAdapter_readBytes_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_buffer_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(buffer, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)buffer, (const void*)cmock_call_instance->ReturnThruPtr_buffer_Val,
      cmock_call_instance->ReturnThruPtr_buffer_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_FlashAdapter_readBytes(CMOCK_FlashAdapter_readBytes_CALL_INSTANCE* cmock_call_instance, uint32_t address, uint8_t* buffer, int buffer_Depth, uint32_t length);
void CMockExpectParameters_FlashAdapter_readBytes(CMOCK_FlashAdapter_readBytes_CALL_INSTANCE* cmock_call_instance, uint32_t address, uint8_t* buffer, int buffer_Depth, uint32_t length)
{
  cmock_call_instance->Expected_address = address;
  cmock_call_instance->IgnoreArg_address = 0;
  cmock_call_instance->Expected_buffer = buffer;
  cmock_call_instance->Expected_buffer_Depth = buffer_Depth;
  cmock_call_instance->IgnoreArg_buffer = 0;
  cmock_call_instance->ReturnThruPtr_buffer_Used = 0;
  cmock_call_instance->Expected_length = length;
  cmock_call_instance->IgnoreArg_length = 0;
}

void FlashAdapter_readBytes_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_readBytes_CALL_INSTANCE));
  CMOCK_FlashAdapter_readBytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_readBytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_readBytes_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_readBytes_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_readBytes_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.FlashAdapter_readBytes_IgnoreBool = (char)1;
}

void FlashAdapter_readBytes_CMockStopIgnore(void)
{
  if(Mock.FlashAdapter_readBytes_IgnoreBool)
    Mock.FlashAdapter_readBytes_CallInstance = CMock_Guts_MemNext(Mock.FlashAdapter_readBytes_CallInstance);
  Mock.FlashAdapter_readBytes_IgnoreBool = (char)0;
}

void FlashAdapter_readBytes_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_readBytes_CALL_INSTANCE));
  CMOCK_FlashAdapter_readBytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_readBytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_readBytes_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_readBytes_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_readBytes_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void FlashAdapter_readBytes_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t address, uint8_t* buffer, uint32_t length, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_readBytes_CALL_INSTANCE));
  CMOCK_FlashAdapter_readBytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_readBytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_readBytes_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_readBytes_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_readBytes_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_FlashAdapter_readBytes(cmock_call_instance, address, buffer, 1, length);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void FlashAdapter_readBytes_AddCallback(CMOCK_FlashAdapter_readBytes_CALLBACK Callback)
{
  Mock.FlashAdapter_readBytes_IgnoreBool = (char)0;
  Mock.FlashAdapter_readBytes_CallbackBool = (char)1;
  Mock.FlashAdapter_readBytes_CallbackFunctionPointer = Callback;
}

void FlashAdapter_readBytes_Stub(CMOCK_FlashAdapter_readBytes_CALLBACK Callback)
{
  Mock.FlashAdapter_readBytes_IgnoreBool = (char)0;
  Mock.FlashAdapter_readBytes_CallbackBool = (char)0;
  Mock.FlashAdapter_readBytes_CallbackFunctionPointer = Callback;
}

void FlashAdapter_readBytes_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t address, uint8_t* buffer, int buffer_Depth, uint32_t length, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_readBytes_CALL_INSTANCE));
  CMOCK_FlashAdapter_readBytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_readBytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_readBytes_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_readBytes_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_readBytes_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_FlashAdapter_readBytes(cmock_call_instance, address, buffer, buffer_Depth, length);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void FlashAdapter_readBytes_CMockReturnMemThruPtr_buffer(UNITY_LINE_TYPE cmock_line, uint8_t const* buffer, size_t cmock_size)
{
  CMOCK_FlashAdapter_readBytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_readBytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.FlashAdapter_readBytes_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_buffer_Used = 1;
  cmock_call_instance->ReturnThruPtr_buffer_Val = buffer;
  cmock_call_instance->ReturnThruPtr_buffer_Size = cmock_size;
}

void FlashAdapter_readBytes_CMockIgnoreArg_address(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_FlashAdapter_readBytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_readBytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.FlashAdapter_readBytes_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_address = 1;
}

void FlashAdapter_readBytes_CMockIgnoreArg_buffer(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_FlashAdapter_readBytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_readBytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.FlashAdapter_readBytes_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_buffer = 1;
}

void FlashAdapter_readBytes_CMockIgnoreArg_length(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_FlashAdapter_readBytes_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_readBytes_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.FlashAdapter_readBytes_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_length = 1;
}

bool FlashAdapter_finish(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FlashAdapter_finish_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FlashAdapter_finish);
  cmock_call_instance = (CMOCK_FlashAdapter_finish_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FlashAdapter_finish_CallInstance);
  Mock.FlashAdapter_finish_CallInstance = CMock_Guts_MemNext(Mock.FlashAdapter_finish_CallInstance);
  if (Mock.FlashAdapter_finish_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.FlashAdapter_finish_FinalReturn;
    Mock.FlashAdapter_finish_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.FlashAdapter_finish_CallbackBool &&
      Mock.FlashAdapter_finish_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.FlashAdapter_finish_CallbackFunctionPointer(Mock.FlashAdapter_finish_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.FlashAdapter_finish_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.FlashAdapter_finish_CallbackFunctionPointer(Mock.FlashAdapter_finish_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void FlashAdapter_finish_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_finish_CALL_INSTANCE));
  CMOCK_FlashAdapter_finish_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_finish_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_finish_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_finish_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_finish_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.FlashAdapter_finish_IgnoreBool = (char)1;
}

void FlashAdapter_finish_CMockStopIgnore(void)
{
  if(Mock.FlashAdapter_finish_IgnoreBool)
    Mock.FlashAdapter_finish_CallInstance = CMock_Guts_MemNext(Mock.FlashAdapter_finish_CallInstance);
  Mock.FlashAdapter_finish_IgnoreBool = (char)0;
}

void FlashAdapter_finish_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_finish_CALL_INSTANCE));
  CMOCK_FlashAdapter_finish_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_finish_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_finish_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_finish_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_finish_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void FlashAdapter_finish_AddCallback(CMOCK_FlashAdapter_finish_CALLBACK Callback)
{
  Mock.FlashAdapter_finish_IgnoreBool = (char)0;
  Mock.FlashAdapter_finish_CallbackBool = (char)1;
  Mock.FlashAdapter_finish_CallbackFunctionPointer = Callback;
}

void FlashAdapter_finish_Stub(CMOCK_FlashAdapter_finish_CALLBACK Callback)
{
  Mock.FlashAdapter_finish_IgnoreBool = (char)0;
  Mock.FlashAdapter_finish_CallbackBool = (char)0;
  Mock.FlashAdapter_finish_CallbackFunctionPointer = Callback;
}

bool FlashAdapter_isFlashRDPProtected(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FlashAdapter_isFlashRDPProtected_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FlashAdapter_isFlashRDPProtected);
  cmock_call_instance = (CMOCK_FlashAdapter_isFlashRDPProtected_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FlashAdapter_isFlashRDPProtected_CallInstance);
  Mock.FlashAdapter_isFlashRDPProtected_CallInstance = CMock_Guts_MemNext(Mock.FlashAdapter_isFlashRDPProtected_CallInstance);
  if (Mock.FlashAdapter_isFlashRDPProtected_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.FlashAdapter_isFlashRDPProtected_FinalReturn;
    Mock.FlashAdapter_isFlashRDPProtected_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.FlashAdapter_isFlashRDPProtected_CallbackBool &&
      Mock.FlashAdapter_isFlashRDPProtected_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.FlashAdapter_isFlashRDPProtected_CallbackFunctionPointer(Mock.FlashAdapter_isFlashRDPProtected_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.FlashAdapter_isFlashRDPProtected_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.FlashAdapter_isFlashRDPProtected_CallbackFunctionPointer(Mock.FlashAdapter_isFlashRDPProtected_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void FlashAdapter_isFlashRDPProtected_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_isFlashRDPProtected_CALL_INSTANCE));
  CMOCK_FlashAdapter_isFlashRDPProtected_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_isFlashRDPProtected_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_isFlashRDPProtected_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_isFlashRDPProtected_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_isFlashRDPProtected_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.FlashAdapter_isFlashRDPProtected_IgnoreBool = (char)1;
}

void FlashAdapter_isFlashRDPProtected_CMockStopIgnore(void)
{
  if(Mock.FlashAdapter_isFlashRDPProtected_IgnoreBool)
    Mock.FlashAdapter_isFlashRDPProtected_CallInstance = CMock_Guts_MemNext(Mock.FlashAdapter_isFlashRDPProtected_CallInstance);
  Mock.FlashAdapter_isFlashRDPProtected_IgnoreBool = (char)0;
}

void FlashAdapter_isFlashRDPProtected_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_isFlashRDPProtected_CALL_INSTANCE));
  CMOCK_FlashAdapter_isFlashRDPProtected_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_isFlashRDPProtected_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_isFlashRDPProtected_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_isFlashRDPProtected_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_isFlashRDPProtected_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void FlashAdapter_isFlashRDPProtected_AddCallback(CMOCK_FlashAdapter_isFlashRDPProtected_CALLBACK Callback)
{
  Mock.FlashAdapter_isFlashRDPProtected_IgnoreBool = (char)0;
  Mock.FlashAdapter_isFlashRDPProtected_CallbackBool = (char)1;
  Mock.FlashAdapter_isFlashRDPProtected_CallbackFunctionPointer = Callback;
}

void FlashAdapter_isFlashRDPProtected_Stub(CMOCK_FlashAdapter_isFlashRDPProtected_CALLBACK Callback)
{
  Mock.FlashAdapter_isFlashRDPProtected_IgnoreBool = (char)0;
  Mock.FlashAdapter_isFlashRDPProtected_CallbackBool = (char)0;
  Mock.FlashAdapter_isFlashRDPProtected_CallbackFunctionPointer = Callback;
}

bool FlashAdapter_isFlashPCROPProtected(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FlashAdapter_isFlashPCROPProtected_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FlashAdapter_isFlashPCROPProtected);
  cmock_call_instance = (CMOCK_FlashAdapter_isFlashPCROPProtected_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FlashAdapter_isFlashPCROPProtected_CallInstance);
  Mock.FlashAdapter_isFlashPCROPProtected_CallInstance = CMock_Guts_MemNext(Mock.FlashAdapter_isFlashPCROPProtected_CallInstance);
  if (Mock.FlashAdapter_isFlashPCROPProtected_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.FlashAdapter_isFlashPCROPProtected_FinalReturn;
    Mock.FlashAdapter_isFlashPCROPProtected_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.FlashAdapter_isFlashPCROPProtected_CallbackBool &&
      Mock.FlashAdapter_isFlashPCROPProtected_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.FlashAdapter_isFlashPCROPProtected_CallbackFunctionPointer(Mock.FlashAdapter_isFlashPCROPProtected_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.FlashAdapter_isFlashPCROPProtected_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.FlashAdapter_isFlashPCROPProtected_CallbackFunctionPointer(Mock.FlashAdapter_isFlashPCROPProtected_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void FlashAdapter_isFlashPCROPProtected_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_isFlashPCROPProtected_CALL_INSTANCE));
  CMOCK_FlashAdapter_isFlashPCROPProtected_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_isFlashPCROPProtected_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_isFlashPCROPProtected_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_isFlashPCROPProtected_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_isFlashPCROPProtected_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.FlashAdapter_isFlashPCROPProtected_IgnoreBool = (char)1;
}

void FlashAdapter_isFlashPCROPProtected_CMockStopIgnore(void)
{
  if(Mock.FlashAdapter_isFlashPCROPProtected_IgnoreBool)
    Mock.FlashAdapter_isFlashPCROPProtected_CallInstance = CMock_Guts_MemNext(Mock.FlashAdapter_isFlashPCROPProtected_CallInstance);
  Mock.FlashAdapter_isFlashPCROPProtected_IgnoreBool = (char)0;
}

void FlashAdapter_isFlashPCROPProtected_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_isFlashPCROPProtected_CALL_INSTANCE));
  CMOCK_FlashAdapter_isFlashPCROPProtected_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_isFlashPCROPProtected_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_isFlashPCROPProtected_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_isFlashPCROPProtected_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_isFlashPCROPProtected_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void FlashAdapter_isFlashPCROPProtected_AddCallback(CMOCK_FlashAdapter_isFlashPCROPProtected_CALLBACK Callback)
{
  Mock.FlashAdapter_isFlashPCROPProtected_IgnoreBool = (char)0;
  Mock.FlashAdapter_isFlashPCROPProtected_CallbackBool = (char)1;
  Mock.FlashAdapter_isFlashPCROPProtected_CallbackFunctionPointer = Callback;
}

void FlashAdapter_isFlashPCROPProtected_Stub(CMOCK_FlashAdapter_isFlashPCROPProtected_CALLBACK Callback)
{
  Mock.FlashAdapter_isFlashPCROPProtected_IgnoreBool = (char)0;
  Mock.FlashAdapter_isFlashPCROPProtected_CallbackBool = (char)0;
  Mock.FlashAdapter_isFlashPCROPProtected_CallbackFunctionPointer = Callback;
}

bool FlashAdapter_setReadProtection(bool enable)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FlashAdapter_setReadProtection_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FlashAdapter_setReadProtection);
  cmock_call_instance = (CMOCK_FlashAdapter_setReadProtection_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FlashAdapter_setReadProtection_CallInstance);
  Mock.FlashAdapter_setReadProtection_CallInstance = CMock_Guts_MemNext(Mock.FlashAdapter_setReadProtection_CallInstance);
  if (Mock.FlashAdapter_setReadProtection_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.FlashAdapter_setReadProtection_FinalReturn;
    Mock.FlashAdapter_setReadProtection_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.FlashAdapter_setReadProtection_CallbackBool &&
      Mock.FlashAdapter_setReadProtection_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.FlashAdapter_setReadProtection_CallbackFunctionPointer(enable, Mock.FlashAdapter_setReadProtection_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_enable)
  {
    UNITY_SET_DETAILS(CMockString_FlashAdapter_setReadProtection,CMockString_enable);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_enable, enable, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.FlashAdapter_setReadProtection_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.FlashAdapter_setReadProtection_CallbackFunctionPointer(enable, Mock.FlashAdapter_setReadProtection_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_FlashAdapter_setReadProtection(CMOCK_FlashAdapter_setReadProtection_CALL_INSTANCE* cmock_call_instance, bool enable);
void CMockExpectParameters_FlashAdapter_setReadProtection(CMOCK_FlashAdapter_setReadProtection_CALL_INSTANCE* cmock_call_instance, bool enable)
{
  cmock_call_instance->Expected_enable = enable;
  cmock_call_instance->IgnoreArg_enable = 0;
}

void FlashAdapter_setReadProtection_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_setReadProtection_CALL_INSTANCE));
  CMOCK_FlashAdapter_setReadProtection_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_setReadProtection_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_setReadProtection_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_setReadProtection_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_setReadProtection_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.FlashAdapter_setReadProtection_IgnoreBool = (char)1;
}

void FlashAdapter_setReadProtection_CMockStopIgnore(void)
{
  if(Mock.FlashAdapter_setReadProtection_IgnoreBool)
    Mock.FlashAdapter_setReadProtection_CallInstance = CMock_Guts_MemNext(Mock.FlashAdapter_setReadProtection_CallInstance);
  Mock.FlashAdapter_setReadProtection_IgnoreBool = (char)0;
}

void FlashAdapter_setReadProtection_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_setReadProtection_CALL_INSTANCE));
  CMOCK_FlashAdapter_setReadProtection_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_setReadProtection_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_setReadProtection_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_setReadProtection_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_setReadProtection_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void FlashAdapter_setReadProtection_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool enable, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_setReadProtection_CALL_INSTANCE));
  CMOCK_FlashAdapter_setReadProtection_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_setReadProtection_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_setReadProtection_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_setReadProtection_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_setReadProtection_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_FlashAdapter_setReadProtection(cmock_call_instance, enable);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void FlashAdapter_setReadProtection_AddCallback(CMOCK_FlashAdapter_setReadProtection_CALLBACK Callback)
{
  Mock.FlashAdapter_setReadProtection_IgnoreBool = (char)0;
  Mock.FlashAdapter_setReadProtection_CallbackBool = (char)1;
  Mock.FlashAdapter_setReadProtection_CallbackFunctionPointer = Callback;
}

void FlashAdapter_setReadProtection_Stub(CMOCK_FlashAdapter_setReadProtection_CALLBACK Callback)
{
  Mock.FlashAdapter_setReadProtection_IgnoreBool = (char)0;
  Mock.FlashAdapter_setReadProtection_CallbackBool = (char)0;
  Mock.FlashAdapter_setReadProtection_CallbackFunctionPointer = Callback;
}

void FlashAdapter_setReadProtection_CMockIgnoreArg_enable(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_FlashAdapter_setReadProtection_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_setReadProtection_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.FlashAdapter_setReadProtection_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_enable = 1;
}

bool FlashAdapter_setPCROP(bool enable, uint32_t protect_address_start, uint32_t protect_address_end)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FlashAdapter_setPCROP_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FlashAdapter_setPCROP);
  cmock_call_instance = (CMOCK_FlashAdapter_setPCROP_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FlashAdapter_setPCROP_CallInstance);
  Mock.FlashAdapter_setPCROP_CallInstance = CMock_Guts_MemNext(Mock.FlashAdapter_setPCROP_CallInstance);
  if (Mock.FlashAdapter_setPCROP_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.FlashAdapter_setPCROP_FinalReturn;
    Mock.FlashAdapter_setPCROP_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.FlashAdapter_setPCROP_CallbackBool &&
      Mock.FlashAdapter_setPCROP_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.FlashAdapter_setPCROP_CallbackFunctionPointer(enable, protect_address_start, protect_address_end, Mock.FlashAdapter_setPCROP_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_enable)
  {
    UNITY_SET_DETAILS(CMockString_FlashAdapter_setPCROP,CMockString_enable);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_enable, enable, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_protect_address_start)
  {
    UNITY_SET_DETAILS(CMockString_FlashAdapter_setPCROP,CMockString_protect_address_start);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_protect_address_start, protect_address_start, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_protect_address_end)
  {
    UNITY_SET_DETAILS(CMockString_FlashAdapter_setPCROP,CMockString_protect_address_end);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_protect_address_end, protect_address_end, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.FlashAdapter_setPCROP_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.FlashAdapter_setPCROP_CallbackFunctionPointer(enable, protect_address_start, protect_address_end, Mock.FlashAdapter_setPCROP_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_FlashAdapter_setPCROP(CMOCK_FlashAdapter_setPCROP_CALL_INSTANCE* cmock_call_instance, bool enable, uint32_t protect_address_start, uint32_t protect_address_end);
void CMockExpectParameters_FlashAdapter_setPCROP(CMOCK_FlashAdapter_setPCROP_CALL_INSTANCE* cmock_call_instance, bool enable, uint32_t protect_address_start, uint32_t protect_address_end)
{
  cmock_call_instance->Expected_enable = enable;
  cmock_call_instance->IgnoreArg_enable = 0;
  cmock_call_instance->Expected_protect_address_start = protect_address_start;
  cmock_call_instance->IgnoreArg_protect_address_start = 0;
  cmock_call_instance->Expected_protect_address_end = protect_address_end;
  cmock_call_instance->IgnoreArg_protect_address_end = 0;
}

void FlashAdapter_setPCROP_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_setPCROP_CALL_INSTANCE));
  CMOCK_FlashAdapter_setPCROP_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_setPCROP_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_setPCROP_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_setPCROP_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_setPCROP_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.FlashAdapter_setPCROP_IgnoreBool = (char)1;
}

void FlashAdapter_setPCROP_CMockStopIgnore(void)
{
  if(Mock.FlashAdapter_setPCROP_IgnoreBool)
    Mock.FlashAdapter_setPCROP_CallInstance = CMock_Guts_MemNext(Mock.FlashAdapter_setPCROP_CallInstance);
  Mock.FlashAdapter_setPCROP_IgnoreBool = (char)0;
}

void FlashAdapter_setPCROP_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_setPCROP_CALL_INSTANCE));
  CMOCK_FlashAdapter_setPCROP_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_setPCROP_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_setPCROP_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_setPCROP_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_setPCROP_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void FlashAdapter_setPCROP_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool enable, uint32_t protect_address_start, uint32_t protect_address_end, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FlashAdapter_setPCROP_CALL_INSTANCE));
  CMOCK_FlashAdapter_setPCROP_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_setPCROP_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FlashAdapter_setPCROP_CallInstance = CMock_Guts_MemChain(Mock.FlashAdapter_setPCROP_CallInstance, cmock_guts_index);
  Mock.FlashAdapter_setPCROP_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_FlashAdapter_setPCROP(cmock_call_instance, enable, protect_address_start, protect_address_end);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void FlashAdapter_setPCROP_AddCallback(CMOCK_FlashAdapter_setPCROP_CALLBACK Callback)
{
  Mock.FlashAdapter_setPCROP_IgnoreBool = (char)0;
  Mock.FlashAdapter_setPCROP_CallbackBool = (char)1;
  Mock.FlashAdapter_setPCROP_CallbackFunctionPointer = Callback;
}

void FlashAdapter_setPCROP_Stub(CMOCK_FlashAdapter_setPCROP_CALLBACK Callback)
{
  Mock.FlashAdapter_setPCROP_IgnoreBool = (char)0;
  Mock.FlashAdapter_setPCROP_CallbackBool = (char)0;
  Mock.FlashAdapter_setPCROP_CallbackFunctionPointer = Callback;
}

void FlashAdapter_setPCROP_CMockIgnoreArg_enable(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_FlashAdapter_setPCROP_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_setPCROP_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.FlashAdapter_setPCROP_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_enable = 1;
}

void FlashAdapter_setPCROP_CMockIgnoreArg_protect_address_start(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_FlashAdapter_setPCROP_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_setPCROP_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.FlashAdapter_setPCROP_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_protect_address_start = 1;
}

void FlashAdapter_setPCROP_CMockIgnoreArg_protect_address_end(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_FlashAdapter_setPCROP_CALL_INSTANCE* cmock_call_instance = (CMOCK_FlashAdapter_setPCROP_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.FlashAdapter_setPCROP_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_protect_address_end = 1;
}

