/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_software_info.h"

static const char* CMockString_SwInfo_getDataJson = "SwInfo_getDataJson";
static const char* CMockString_SwInfo_getVersion = "SwInfo_getVersion";
static const char* CMockString_buffer = "buffer";
static const char* CMockString_size = "size";

typedef struct _CMOCK_SwInfo_getDataJson_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;
  uint8_t* Expected_buffer;
  uint16_t Expected_size;
  int Expected_buffer_Depth;
  char ReturnThruPtr_buffer_Used;
  uint8_t const* ReturnThruPtr_buffer_Val;
  size_t ReturnThruPtr_buffer_Size;
  char IgnoreArg_buffer;
  char IgnoreArg_size;

} CMOCK_SwInfo_getDataJson_CALL_INSTANCE;

typedef struct _CMOCK_SwInfo_getVersion_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;
  uint8_t* Expected_buffer;
  uint16_t Expected_size;
  int Expected_buffer_Depth;
  char ReturnThruPtr_buffer_Used;
  uint8_t const* ReturnThruPtr_buffer_Val;
  size_t ReturnThruPtr_buffer_Size;
  char IgnoreArg_buffer;
  char IgnoreArg_size;

} CMOCK_SwInfo_getVersion_CALL_INSTANCE;

static struct mock_software_infoInstance
{
  char SwInfo_getDataJson_IgnoreBool;
  bool SwInfo_getDataJson_FinalReturn;
  char SwInfo_getDataJson_CallbackBool;
  CMOCK_SwInfo_getDataJson_CALLBACK SwInfo_getDataJson_CallbackFunctionPointer;
  int SwInfo_getDataJson_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SwInfo_getDataJson_CallInstance;
  char SwInfo_getVersion_IgnoreBool;
  bool SwInfo_getVersion_FinalReturn;
  char SwInfo_getVersion_CallbackBool;
  CMOCK_SwInfo_getVersion_CALLBACK SwInfo_getVersion_CallbackFunctionPointer;
  int SwInfo_getVersion_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SwInfo_getVersion_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_software_info_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.SwInfo_getDataJson_CallInstance;
  if (Mock.SwInfo_getDataJson_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SwInfo_getDataJson);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SwInfo_getDataJson_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.SwInfo_getVersion_CallInstance;
  if (Mock.SwInfo_getVersion_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SwInfo_getVersion);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SwInfo_getVersion_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_software_info_Init(void)
{
  mock_software_info_Destroy();
}

void mock_software_info_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

bool SwInfo_getDataJson(uint8_t* buffer, uint16_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SwInfo_getDataJson_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SwInfo_getDataJson);
  cmock_call_instance = (CMOCK_SwInfo_getDataJson_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SwInfo_getDataJson_CallInstance);
  Mock.SwInfo_getDataJson_CallInstance = CMock_Guts_MemNext(Mock.SwInfo_getDataJson_CallInstance);
  if (Mock.SwInfo_getDataJson_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.SwInfo_getDataJson_FinalReturn;
    Mock.SwInfo_getDataJson_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.SwInfo_getDataJson_CallbackBool &&
      Mock.SwInfo_getDataJson_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.SwInfo_getDataJson_CallbackFunctionPointer(buffer, size, Mock.SwInfo_getDataJson_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_buffer)
  {
    UNITY_SET_DETAILS(CMockString_SwInfo_getDataJson,CMockString_buffer);
    if (cmock_call_instance->Expected_buffer == NULL)
      { UNITY_TEST_ASSERT_NULL(buffer, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_buffer, buffer, cmock_call_instance->Expected_buffer_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_size)
  {
    UNITY_SET_DETAILS(CMockString_SwInfo_getDataJson,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_size, size, cmock_line, CMockStringMismatch);
  }
  if (Mock.SwInfo_getDataJson_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.SwInfo_getDataJson_CallbackFunctionPointer(buffer, size, Mock.SwInfo_getDataJson_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_buffer_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(buffer, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)buffer, (const void*)cmock_call_instance->ReturnThruPtr_buffer_Val,
      cmock_call_instance->ReturnThruPtr_buffer_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SwInfo_getDataJson(CMOCK_SwInfo_getDataJson_CALL_INSTANCE* cmock_call_instance, uint8_t* buffer, int buffer_Depth, uint16_t size);
void CMockExpectParameters_SwInfo_getDataJson(CMOCK_SwInfo_getDataJson_CALL_INSTANCE* cmock_call_instance, uint8_t* buffer, int buffer_Depth, uint16_t size)
{
  cmock_call_instance->Expected_buffer = buffer;
  cmock_call_instance->Expected_buffer_Depth = buffer_Depth;
  cmock_call_instance->IgnoreArg_buffer = 0;
  cmock_call_instance->ReturnThruPtr_buffer_Used = 0;
  cmock_call_instance->Expected_size = size;
  cmock_call_instance->IgnoreArg_size = 0;
}

void SwInfo_getDataJson_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SwInfo_getDataJson_CALL_INSTANCE));
  CMOCK_SwInfo_getDataJson_CALL_INSTANCE* cmock_call_instance = (CMOCK_SwInfo_getDataJson_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SwInfo_getDataJson_CallInstance = CMock_Guts_MemChain(Mock.SwInfo_getDataJson_CallInstance, cmock_guts_index);
  Mock.SwInfo_getDataJson_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.SwInfo_getDataJson_IgnoreBool = (char)1;
}

void SwInfo_getDataJson_CMockStopIgnore(void)
{
  if(Mock.SwInfo_getDataJson_IgnoreBool)
    Mock.SwInfo_getDataJson_CallInstance = CMock_Guts_MemNext(Mock.SwInfo_getDataJson_CallInstance);
  Mock.SwInfo_getDataJson_IgnoreBool = (char)0;
}

void SwInfo_getDataJson_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* buffer, uint16_t size, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SwInfo_getDataJson_CALL_INSTANCE));
  CMOCK_SwInfo_getDataJson_CALL_INSTANCE* cmock_call_instance = (CMOCK_SwInfo_getDataJson_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SwInfo_getDataJson_CallInstance = CMock_Guts_MemChain(Mock.SwInfo_getDataJson_CallInstance, cmock_guts_index);
  Mock.SwInfo_getDataJson_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_SwInfo_getDataJson(cmock_call_instance, buffer, 1, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void SwInfo_getDataJson_AddCallback(CMOCK_SwInfo_getDataJson_CALLBACK Callback)
{
  Mock.SwInfo_getDataJson_IgnoreBool = (char)0;
  Mock.SwInfo_getDataJson_CallbackBool = (char)1;
  Mock.SwInfo_getDataJson_CallbackFunctionPointer = Callback;
}

void SwInfo_getDataJson_Stub(CMOCK_SwInfo_getDataJson_CALLBACK Callback)
{
  Mock.SwInfo_getDataJson_IgnoreBool = (char)0;
  Mock.SwInfo_getDataJson_CallbackBool = (char)0;
  Mock.SwInfo_getDataJson_CallbackFunctionPointer = Callback;
}

void SwInfo_getDataJson_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* buffer, int buffer_Depth, uint16_t size, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SwInfo_getDataJson_CALL_INSTANCE));
  CMOCK_SwInfo_getDataJson_CALL_INSTANCE* cmock_call_instance = (CMOCK_SwInfo_getDataJson_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SwInfo_getDataJson_CallInstance = CMock_Guts_MemChain(Mock.SwInfo_getDataJson_CallInstance, cmock_guts_index);
  Mock.SwInfo_getDataJson_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_SwInfo_getDataJson(cmock_call_instance, buffer, buffer_Depth, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void SwInfo_getDataJson_CMockReturnMemThruPtr_buffer(UNITY_LINE_TYPE cmock_line, uint8_t const* buffer, size_t cmock_size)
{
  CMOCK_SwInfo_getDataJson_CALL_INSTANCE* cmock_call_instance = (CMOCK_SwInfo_getDataJson_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SwInfo_getDataJson_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_buffer_Used = 1;
  cmock_call_instance->ReturnThruPtr_buffer_Val = buffer;
  cmock_call_instance->ReturnThruPtr_buffer_Size = cmock_size;
}

void SwInfo_getDataJson_CMockIgnoreArg_buffer(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SwInfo_getDataJson_CALL_INSTANCE* cmock_call_instance = (CMOCK_SwInfo_getDataJson_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SwInfo_getDataJson_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_buffer = 1;
}

void SwInfo_getDataJson_CMockIgnoreArg_size(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SwInfo_getDataJson_CALL_INSTANCE* cmock_call_instance = (CMOCK_SwInfo_getDataJson_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SwInfo_getDataJson_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_size = 1;
}

bool SwInfo_getVersion(uint8_t* buffer, uint16_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SwInfo_getVersion_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SwInfo_getVersion);
  cmock_call_instance = (CMOCK_SwInfo_getVersion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SwInfo_getVersion_CallInstance);
  Mock.SwInfo_getVersion_CallInstance = CMock_Guts_MemNext(Mock.SwInfo_getVersion_CallInstance);
  if (Mock.SwInfo_getVersion_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.SwInfo_getVersion_FinalReturn;
    Mock.SwInfo_getVersion_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.SwInfo_getVersion_CallbackBool &&
      Mock.SwInfo_getVersion_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.SwInfo_getVersion_CallbackFunctionPointer(buffer, size, Mock.SwInfo_getVersion_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_buffer)
  {
    UNITY_SET_DETAILS(CMockString_SwInfo_getVersion,CMockString_buffer);
    if (cmock_call_instance->Expected_buffer == NULL)
      { UNITY_TEST_ASSERT_NULL(buffer, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_buffer, buffer, cmock_call_instance->Expected_buffer_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_size)
  {
    UNITY_SET_DETAILS(CMockString_SwInfo_getVersion,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_size, size, cmock_line, CMockStringMismatch);
  }
  if (Mock.SwInfo_getVersion_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.SwInfo_getVersion_CallbackFunctionPointer(buffer, size, Mock.SwInfo_getVersion_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_buffer_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(buffer, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)buffer, (const void*)cmock_call_instance->ReturnThruPtr_buffer_Val,
      cmock_call_instance->ReturnThruPtr_buffer_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SwInfo_getVersion(CMOCK_SwInfo_getVersion_CALL_INSTANCE* cmock_call_instance, uint8_t* buffer, int buffer_Depth, uint16_t size);
void CMockExpectParameters_SwInfo_getVersion(CMOCK_SwInfo_getVersion_CALL_INSTANCE* cmock_call_instance, uint8_t* buffer, int buffer_Depth, uint16_t size)
{
  cmock_call_instance->Expected_buffer = buffer;
  cmock_call_instance->Expected_buffer_Depth = buffer_Depth;
  cmock_call_instance->IgnoreArg_buffer = 0;
  cmock_call_instance->ReturnThruPtr_buffer_Used = 0;
  cmock_call_instance->Expected_size = size;
  cmock_call_instance->IgnoreArg_size = 0;
}

void SwInfo_getVersion_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SwInfo_getVersion_CALL_INSTANCE));
  CMOCK_SwInfo_getVersion_CALL_INSTANCE* cmock_call_instance = (CMOCK_SwInfo_getVersion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SwInfo_getVersion_CallInstance = CMock_Guts_MemChain(Mock.SwInfo_getVersion_CallInstance, cmock_guts_index);
  Mock.SwInfo_getVersion_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.SwInfo_getVersion_IgnoreBool = (char)1;
}

void SwInfo_getVersion_CMockStopIgnore(void)
{
  if(Mock.SwInfo_getVersion_IgnoreBool)
    Mock.SwInfo_getVersion_CallInstance = CMock_Guts_MemNext(Mock.SwInfo_getVersion_CallInstance);
  Mock.SwInfo_getVersion_IgnoreBool = (char)0;
}

void SwInfo_getVersion_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* buffer, uint16_t size, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SwInfo_getVersion_CALL_INSTANCE));
  CMOCK_SwInfo_getVersion_CALL_INSTANCE* cmock_call_instance = (CMOCK_SwInfo_getVersion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SwInfo_getVersion_CallInstance = CMock_Guts_MemChain(Mock.SwInfo_getVersion_CallInstance, cmock_guts_index);
  Mock.SwInfo_getVersion_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_SwInfo_getVersion(cmock_call_instance, buffer, 1, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void SwInfo_getVersion_AddCallback(CMOCK_SwInfo_getVersion_CALLBACK Callback)
{
  Mock.SwInfo_getVersion_IgnoreBool = (char)0;
  Mock.SwInfo_getVersion_CallbackBool = (char)1;
  Mock.SwInfo_getVersion_CallbackFunctionPointer = Callback;
}

void SwInfo_getVersion_Stub(CMOCK_SwInfo_getVersion_CALLBACK Callback)
{
  Mock.SwInfo_getVersion_IgnoreBool = (char)0;
  Mock.SwInfo_getVersion_CallbackBool = (char)0;
  Mock.SwInfo_getVersion_CallbackFunctionPointer = Callback;
}

void SwInfo_getVersion_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* buffer, int buffer_Depth, uint16_t size, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SwInfo_getVersion_CALL_INSTANCE));
  CMOCK_SwInfo_getVersion_CALL_INSTANCE* cmock_call_instance = (CMOCK_SwInfo_getVersion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SwInfo_getVersion_CallInstance = CMock_Guts_MemChain(Mock.SwInfo_getVersion_CallInstance, cmock_guts_index);
  Mock.SwInfo_getVersion_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_SwInfo_getVersion(cmock_call_instance, buffer, buffer_Depth, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void SwInfo_getVersion_CMockReturnMemThruPtr_buffer(UNITY_LINE_TYPE cmock_line, uint8_t const* buffer, size_t cmock_size)
{
  CMOCK_SwInfo_getVersion_CALL_INSTANCE* cmock_call_instance = (CMOCK_SwInfo_getVersion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SwInfo_getVersion_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_buffer_Used = 1;
  cmock_call_instance->ReturnThruPtr_buffer_Val = buffer;
  cmock_call_instance->ReturnThruPtr_buffer_Size = cmock_size;
}

void SwInfo_getVersion_CMockIgnoreArg_buffer(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SwInfo_getVersion_CALL_INSTANCE* cmock_call_instance = (CMOCK_SwInfo_getVersion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SwInfo_getVersion_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_buffer = 1;
}

void SwInfo_getVersion_CMockIgnoreArg_size(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_SwInfo_getVersion_CALL_INSTANCE* cmock_call_instance = (CMOCK_SwInfo_getVersion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SwInfo_getVersion_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_size = 1;
}

