/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_SYSTEM_ADAPTER_H
#define _MOCK_SYSTEM_ADAPTER_H

#include "unity.h"
#include "system_adapter.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_system_adapter_Init(void);
void mock_system_adapter_Destroy(void);
void mock_system_adapter_Verify(void);




#define SystemAdapter_reset_Ignore() SystemAdapter_reset_CMockIgnore()
void SystemAdapter_reset_CMockIgnore(void);
#define SystemAdapter_reset_StopIgnore() SystemAdapter_reset_CMockStopIgnore()
void SystemAdapter_reset_CMockStopIgnore(void);
#define SystemAdapter_reset_Expect() SystemAdapter_reset_CMockExpect(__LINE__)
void SystemAdapter_reset_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_SystemAdapter_reset_CALLBACK)(int cmock_num_calls);
void SystemAdapter_reset_AddCallback(CMOCK_SystemAdapter_reset_CALLBACK Callback);
void SystemAdapter_reset_Stub(CMOCK_SystemAdapter_reset_CALLBACK Callback);
#define SystemAdapter_reset_StubWithCallback SystemAdapter_reset_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
