/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_MAIN_H
#define _MOCK_MAIN_H

#include "unity.h"
#include "main.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_main_Init(void);
void mock_main_Destroy(void);
void mock_main_Verify(void);




#define Error_Handler_Ignore() Error_Handler_CMockIgnore()
void Error_Handler_CMockIgnore(void);
#define Error_Handler_StopIgnore() Error_Handler_CMockStopIgnore()
void Error_Handler_CMockStopIgnore(void);
#define Error_Handler_Expect() Error_Handler_CMockExpect(__LINE__)
void Error_Handler_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_Error_Handler_CALLBACK)(int cmock_num_calls);
void Error_Handler_AddCallback(CMOCK_Error_Handler_CALLBACK Callback);
void Error_Handler_Stub(CMOCK_Error_Handler_CALLBACK Callback);
#define Error_Handler_StubWithCallback Error_Handler_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
