/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_hash_adapter.h"

static const char* CMockString_BoardInfo_decodeBase64ManufacturerId = "BoardInfo_decodeBase64ManufacturerId";
static const char* CMockString_HashAdapter_getBase64HashedBoardId = "HashAdapter_getBase64HashedBoardId";
static const char* CMockString_HashAdapter_getHashedBoardId = "HashAdapter_getHashedBoardId";
static const char* CMockString_b64_hashed_board_id_str = "b64_hashed_board_id_str";
static const char* CMockString_b64_hashed_board_id_str_size = "b64_hashed_board_id_str_size";
static const char* CMockString_hashed_board_id = "hashed_board_id";
static const char* CMockString_manufacturer_id = "manufacturer_id";

typedef struct _CMOCK_HashAdapter_getHashedBoardId_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint8_t* Expected_hashed_board_id;
  int Expected_hashed_board_id_Depth;
  char ReturnThruPtr_hashed_board_id_Used;
  uint8_t const* ReturnThruPtr_hashed_board_id_Val;
  size_t ReturnThruPtr_hashed_board_id_Size;
  char IgnoreArg_hashed_board_id;

} CMOCK_HashAdapter_getHashedBoardId_CALL_INSTANCE;

typedef struct _CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;
  uint8_t* Expected_b64_hashed_board_id_str;
  size_t Expected_b64_hashed_board_id_str_size;
  int Expected_b64_hashed_board_id_str_Depth;
  char ReturnThruPtr_b64_hashed_board_id_str_Used;
  uint8_t const* ReturnThruPtr_b64_hashed_board_id_str_Val;
  size_t ReturnThruPtr_b64_hashed_board_id_str_Size;
  char IgnoreArg_b64_hashed_board_id_str;
  char IgnoreArg_b64_hashed_board_id_str_size;

} CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE;

typedef struct _CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;
  uint8_t* Expected_manufacturer_id;
  int Expected_manufacturer_id_Depth;
  char ReturnThruPtr_manufacturer_id_Used;
  uint8_t const* ReturnThruPtr_manufacturer_id_Val;
  size_t ReturnThruPtr_manufacturer_id_Size;
  char IgnoreArg_manufacturer_id;

} CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE;

static struct mock_hash_adapterInstance
{
  char HashAdapter_getHashedBoardId_IgnoreBool;
  char HashAdapter_getHashedBoardId_CallbackBool;
  CMOCK_HashAdapter_getHashedBoardId_CALLBACK HashAdapter_getHashedBoardId_CallbackFunctionPointer;
  int HashAdapter_getHashedBoardId_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE HashAdapter_getHashedBoardId_CallInstance;
  char HashAdapter_getBase64HashedBoardId_IgnoreBool;
  bool HashAdapter_getBase64HashedBoardId_FinalReturn;
  char HashAdapter_getBase64HashedBoardId_CallbackBool;
  CMOCK_HashAdapter_getBase64HashedBoardId_CALLBACK HashAdapter_getBase64HashedBoardId_CallbackFunctionPointer;
  int HashAdapter_getBase64HashedBoardId_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE HashAdapter_getBase64HashedBoardId_CallInstance;
  char BoardInfo_decodeBase64ManufacturerId_IgnoreBool;
  bool BoardInfo_decodeBase64ManufacturerId_FinalReturn;
  char BoardInfo_decodeBase64ManufacturerId_CallbackBool;
  CMOCK_BoardInfo_decodeBase64ManufacturerId_CALLBACK BoardInfo_decodeBase64ManufacturerId_CallbackFunctionPointer;
  int BoardInfo_decodeBase64ManufacturerId_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE BoardInfo_decodeBase64ManufacturerId_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_hash_adapter_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.HashAdapter_getHashedBoardId_CallInstance;
  if (Mock.HashAdapter_getHashedBoardId_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HashAdapter_getHashedBoardId);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.HashAdapter_getHashedBoardId_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.HashAdapter_getBase64HashedBoardId_CallInstance;
  if (Mock.HashAdapter_getBase64HashedBoardId_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HashAdapter_getBase64HashedBoardId);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.HashAdapter_getBase64HashedBoardId_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.BoardInfo_decodeBase64ManufacturerId_CallInstance;
  if (Mock.BoardInfo_decodeBase64ManufacturerId_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_BoardInfo_decodeBase64ManufacturerId);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.BoardInfo_decodeBase64ManufacturerId_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_hash_adapter_Init(void)
{
  mock_hash_adapter_Destroy();
}

void mock_hash_adapter_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void HashAdapter_getHashedBoardId(uint8_t* hashed_board_id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HashAdapter_getHashedBoardId_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HashAdapter_getHashedBoardId);
  cmock_call_instance = (CMOCK_HashAdapter_getHashedBoardId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HashAdapter_getHashedBoardId_CallInstance);
  Mock.HashAdapter_getHashedBoardId_CallInstance = CMock_Guts_MemNext(Mock.HashAdapter_getHashedBoardId_CallInstance);
  if (Mock.HashAdapter_getHashedBoardId_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.HashAdapter_getHashedBoardId_CallbackBool &&
      Mock.HashAdapter_getHashedBoardId_CallbackFunctionPointer != NULL)
  {
    Mock.HashAdapter_getHashedBoardId_CallbackFunctionPointer(hashed_board_id, Mock.HashAdapter_getHashedBoardId_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_hashed_board_id)
  {
    UNITY_SET_DETAILS(CMockString_HashAdapter_getHashedBoardId,CMockString_hashed_board_id);
    if (cmock_call_instance->Expected_hashed_board_id == NULL)
      { UNITY_TEST_ASSERT_NULL(hashed_board_id, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_hashed_board_id, hashed_board_id, cmock_call_instance->Expected_hashed_board_id_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.HashAdapter_getHashedBoardId_CallbackFunctionPointer != NULL)
  {
    Mock.HashAdapter_getHashedBoardId_CallbackFunctionPointer(hashed_board_id, Mock.HashAdapter_getHashedBoardId_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_hashed_board_id_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(hashed_board_id, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)hashed_board_id, (const void*)cmock_call_instance->ReturnThruPtr_hashed_board_id_Val,
      cmock_call_instance->ReturnThruPtr_hashed_board_id_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HashAdapter_getHashedBoardId(CMOCK_HashAdapter_getHashedBoardId_CALL_INSTANCE* cmock_call_instance, uint8_t* hashed_board_id, int hashed_board_id_Depth);
void CMockExpectParameters_HashAdapter_getHashedBoardId(CMOCK_HashAdapter_getHashedBoardId_CALL_INSTANCE* cmock_call_instance, uint8_t* hashed_board_id, int hashed_board_id_Depth)
{
  cmock_call_instance->Expected_hashed_board_id = hashed_board_id;
  cmock_call_instance->Expected_hashed_board_id_Depth = hashed_board_id_Depth;
  cmock_call_instance->IgnoreArg_hashed_board_id = 0;
  cmock_call_instance->ReturnThruPtr_hashed_board_id_Used = 0;
}

void HashAdapter_getHashedBoardId_CMockIgnore(void)
{
  Mock.HashAdapter_getHashedBoardId_IgnoreBool = (char)1;
}

void HashAdapter_getHashedBoardId_CMockStopIgnore(void)
{
  Mock.HashAdapter_getHashedBoardId_IgnoreBool = (char)0;
}

void HashAdapter_getHashedBoardId_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HashAdapter_getHashedBoardId_CALL_INSTANCE));
  CMOCK_HashAdapter_getHashedBoardId_CALL_INSTANCE* cmock_call_instance = (CMOCK_HashAdapter_getHashedBoardId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HashAdapter_getHashedBoardId_CallInstance = CMock_Guts_MemChain(Mock.HashAdapter_getHashedBoardId_CallInstance, cmock_guts_index);
  Mock.HashAdapter_getHashedBoardId_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void HashAdapter_getHashedBoardId_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t* hashed_board_id)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HashAdapter_getHashedBoardId_CALL_INSTANCE));
  CMOCK_HashAdapter_getHashedBoardId_CALL_INSTANCE* cmock_call_instance = (CMOCK_HashAdapter_getHashedBoardId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HashAdapter_getHashedBoardId_CallInstance = CMock_Guts_MemChain(Mock.HashAdapter_getHashedBoardId_CallInstance, cmock_guts_index);
  Mock.HashAdapter_getHashedBoardId_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_HashAdapter_getHashedBoardId(cmock_call_instance, hashed_board_id, 1);
}

void HashAdapter_getHashedBoardId_AddCallback(CMOCK_HashAdapter_getHashedBoardId_CALLBACK Callback)
{
  Mock.HashAdapter_getHashedBoardId_IgnoreBool = (char)0;
  Mock.HashAdapter_getHashedBoardId_CallbackBool = (char)1;
  Mock.HashAdapter_getHashedBoardId_CallbackFunctionPointer = Callback;
}

void HashAdapter_getHashedBoardId_Stub(CMOCK_HashAdapter_getHashedBoardId_CALLBACK Callback)
{
  Mock.HashAdapter_getHashedBoardId_IgnoreBool = (char)0;
  Mock.HashAdapter_getHashedBoardId_CallbackBool = (char)0;
  Mock.HashAdapter_getHashedBoardId_CallbackFunctionPointer = Callback;
}

void HashAdapter_getHashedBoardId_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, uint8_t* hashed_board_id, int hashed_board_id_Depth)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HashAdapter_getHashedBoardId_CALL_INSTANCE));
  CMOCK_HashAdapter_getHashedBoardId_CALL_INSTANCE* cmock_call_instance = (CMOCK_HashAdapter_getHashedBoardId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HashAdapter_getHashedBoardId_CallInstance = CMock_Guts_MemChain(Mock.HashAdapter_getHashedBoardId_CallInstance, cmock_guts_index);
  Mock.HashAdapter_getHashedBoardId_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_HashAdapter_getHashedBoardId(cmock_call_instance, hashed_board_id, hashed_board_id_Depth);
}

void HashAdapter_getHashedBoardId_CMockReturnMemThruPtr_hashed_board_id(UNITY_LINE_TYPE cmock_line, uint8_t const* hashed_board_id, size_t cmock_size)
{
  CMOCK_HashAdapter_getHashedBoardId_CALL_INSTANCE* cmock_call_instance = (CMOCK_HashAdapter_getHashedBoardId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.HashAdapter_getHashedBoardId_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_hashed_board_id_Used = 1;
  cmock_call_instance->ReturnThruPtr_hashed_board_id_Val = hashed_board_id;
  cmock_call_instance->ReturnThruPtr_hashed_board_id_Size = cmock_size;
}

void HashAdapter_getHashedBoardId_CMockIgnoreArg_hashed_board_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_HashAdapter_getHashedBoardId_CALL_INSTANCE* cmock_call_instance = (CMOCK_HashAdapter_getHashedBoardId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.HashAdapter_getHashedBoardId_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_hashed_board_id = 1;
}

bool HashAdapter_getBase64HashedBoardId(uint8_t* b64_hashed_board_id_str, size_t b64_hashed_board_id_str_size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HashAdapter_getBase64HashedBoardId);
  cmock_call_instance = (CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HashAdapter_getBase64HashedBoardId_CallInstance);
  Mock.HashAdapter_getBase64HashedBoardId_CallInstance = CMock_Guts_MemNext(Mock.HashAdapter_getBase64HashedBoardId_CallInstance);
  if (Mock.HashAdapter_getBase64HashedBoardId_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.HashAdapter_getBase64HashedBoardId_FinalReturn;
    Mock.HashAdapter_getBase64HashedBoardId_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.HashAdapter_getBase64HashedBoardId_CallbackBool &&
      Mock.HashAdapter_getBase64HashedBoardId_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.HashAdapter_getBase64HashedBoardId_CallbackFunctionPointer(b64_hashed_board_id_str, b64_hashed_board_id_str_size, Mock.HashAdapter_getBase64HashedBoardId_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_b64_hashed_board_id_str)
  {
    UNITY_SET_DETAILS(CMockString_HashAdapter_getBase64HashedBoardId,CMockString_b64_hashed_board_id_str);
    if (cmock_call_instance->Expected_b64_hashed_board_id_str == NULL)
      { UNITY_TEST_ASSERT_NULL(b64_hashed_board_id_str, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_b64_hashed_board_id_str, b64_hashed_board_id_str, cmock_call_instance->Expected_b64_hashed_board_id_str_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_b64_hashed_board_id_str_size)
  {
    UNITY_SET_DETAILS(CMockString_HashAdapter_getBase64HashedBoardId,CMockString_b64_hashed_board_id_str_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_b64_hashed_board_id_str_size), (void*)(&b64_hashed_board_id_str_size), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.HashAdapter_getBase64HashedBoardId_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.HashAdapter_getBase64HashedBoardId_CallbackFunctionPointer(b64_hashed_board_id_str, b64_hashed_board_id_str_size, Mock.HashAdapter_getBase64HashedBoardId_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_b64_hashed_board_id_str_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(b64_hashed_board_id_str, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)b64_hashed_board_id_str, (const void*)cmock_call_instance->ReturnThruPtr_b64_hashed_board_id_str_Val,
      cmock_call_instance->ReturnThruPtr_b64_hashed_board_id_str_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HashAdapter_getBase64HashedBoardId(CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE* cmock_call_instance, uint8_t* b64_hashed_board_id_str, int b64_hashed_board_id_str_Depth, size_t b64_hashed_board_id_str_size);
void CMockExpectParameters_HashAdapter_getBase64HashedBoardId(CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE* cmock_call_instance, uint8_t* b64_hashed_board_id_str, int b64_hashed_board_id_str_Depth, size_t b64_hashed_board_id_str_size)
{
  cmock_call_instance->Expected_b64_hashed_board_id_str = b64_hashed_board_id_str;
  cmock_call_instance->Expected_b64_hashed_board_id_str_Depth = b64_hashed_board_id_str_Depth;
  cmock_call_instance->IgnoreArg_b64_hashed_board_id_str = 0;
  cmock_call_instance->ReturnThruPtr_b64_hashed_board_id_str_Used = 0;
  memcpy((void*)(&cmock_call_instance->Expected_b64_hashed_board_id_str_size), (void*)(&b64_hashed_board_id_str_size),
         sizeof(size_t[sizeof(b64_hashed_board_id_str_size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_b64_hashed_board_id_str_size = 0;
}

void HashAdapter_getBase64HashedBoardId_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE));
  CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE* cmock_call_instance = (CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HashAdapter_getBase64HashedBoardId_CallInstance = CMock_Guts_MemChain(Mock.HashAdapter_getBase64HashedBoardId_CallInstance, cmock_guts_index);
  Mock.HashAdapter_getBase64HashedBoardId_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.HashAdapter_getBase64HashedBoardId_IgnoreBool = (char)1;
}

void HashAdapter_getBase64HashedBoardId_CMockStopIgnore(void)
{
  if(Mock.HashAdapter_getBase64HashedBoardId_IgnoreBool)
    Mock.HashAdapter_getBase64HashedBoardId_CallInstance = CMock_Guts_MemNext(Mock.HashAdapter_getBase64HashedBoardId_CallInstance);
  Mock.HashAdapter_getBase64HashedBoardId_IgnoreBool = (char)0;
}

void HashAdapter_getBase64HashedBoardId_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE));
  CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE* cmock_call_instance = (CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HashAdapter_getBase64HashedBoardId_CallInstance = CMock_Guts_MemChain(Mock.HashAdapter_getBase64HashedBoardId_CallInstance, cmock_guts_index);
  Mock.HashAdapter_getBase64HashedBoardId_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void HashAdapter_getBase64HashedBoardId_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* b64_hashed_board_id_str, size_t b64_hashed_board_id_str_size, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE));
  CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE* cmock_call_instance = (CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HashAdapter_getBase64HashedBoardId_CallInstance = CMock_Guts_MemChain(Mock.HashAdapter_getBase64HashedBoardId_CallInstance, cmock_guts_index);
  Mock.HashAdapter_getBase64HashedBoardId_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_HashAdapter_getBase64HashedBoardId(cmock_call_instance, b64_hashed_board_id_str, b64_hashed_board_id_str_size, b64_hashed_board_id_str_size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void HashAdapter_getBase64HashedBoardId_AddCallback(CMOCK_HashAdapter_getBase64HashedBoardId_CALLBACK Callback)
{
  Mock.HashAdapter_getBase64HashedBoardId_IgnoreBool = (char)0;
  Mock.HashAdapter_getBase64HashedBoardId_CallbackBool = (char)1;
  Mock.HashAdapter_getBase64HashedBoardId_CallbackFunctionPointer = Callback;
}

void HashAdapter_getBase64HashedBoardId_Stub(CMOCK_HashAdapter_getBase64HashedBoardId_CALLBACK Callback)
{
  Mock.HashAdapter_getBase64HashedBoardId_IgnoreBool = (char)0;
  Mock.HashAdapter_getBase64HashedBoardId_CallbackBool = (char)0;
  Mock.HashAdapter_getBase64HashedBoardId_CallbackFunctionPointer = Callback;
}

void HashAdapter_getBase64HashedBoardId_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* b64_hashed_board_id_str, int b64_hashed_board_id_str_Depth, size_t b64_hashed_board_id_str_size, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE));
  CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE* cmock_call_instance = (CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HashAdapter_getBase64HashedBoardId_CallInstance = CMock_Guts_MemChain(Mock.HashAdapter_getBase64HashedBoardId_CallInstance, cmock_guts_index);
  Mock.HashAdapter_getBase64HashedBoardId_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_HashAdapter_getBase64HashedBoardId(cmock_call_instance, b64_hashed_board_id_str, b64_hashed_board_id_str_Depth, b64_hashed_board_id_str_size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void HashAdapter_getBase64HashedBoardId_CMockReturnMemThruPtr_b64_hashed_board_id_str(UNITY_LINE_TYPE cmock_line, uint8_t const* b64_hashed_board_id_str, size_t cmock_size)
{
  CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE* cmock_call_instance = (CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.HashAdapter_getBase64HashedBoardId_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_b64_hashed_board_id_str_Used = 1;
  cmock_call_instance->ReturnThruPtr_b64_hashed_board_id_str_Val = b64_hashed_board_id_str;
  cmock_call_instance->ReturnThruPtr_b64_hashed_board_id_str_Size = cmock_size;
}

void HashAdapter_getBase64HashedBoardId_CMockIgnoreArg_b64_hashed_board_id_str(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE* cmock_call_instance = (CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.HashAdapter_getBase64HashedBoardId_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_b64_hashed_board_id_str = 1;
}

void HashAdapter_getBase64HashedBoardId_CMockIgnoreArg_b64_hashed_board_id_str_size(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE* cmock_call_instance = (CMOCK_HashAdapter_getBase64HashedBoardId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.HashAdapter_getBase64HashedBoardId_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_b64_hashed_board_id_str_size = 1;
}

bool BoardInfo_decodeBase64ManufacturerId(uint8_t* manufacturer_id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_BoardInfo_decodeBase64ManufacturerId);
  cmock_call_instance = (CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.BoardInfo_decodeBase64ManufacturerId_CallInstance);
  Mock.BoardInfo_decodeBase64ManufacturerId_CallInstance = CMock_Guts_MemNext(Mock.BoardInfo_decodeBase64ManufacturerId_CallInstance);
  if (Mock.BoardInfo_decodeBase64ManufacturerId_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.BoardInfo_decodeBase64ManufacturerId_FinalReturn;
    Mock.BoardInfo_decodeBase64ManufacturerId_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.BoardInfo_decodeBase64ManufacturerId_CallbackBool &&
      Mock.BoardInfo_decodeBase64ManufacturerId_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.BoardInfo_decodeBase64ManufacturerId_CallbackFunctionPointer(manufacturer_id, Mock.BoardInfo_decodeBase64ManufacturerId_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_manufacturer_id)
  {
    UNITY_SET_DETAILS(CMockString_BoardInfo_decodeBase64ManufacturerId,CMockString_manufacturer_id);
    if (cmock_call_instance->Expected_manufacturer_id == NULL)
      { UNITY_TEST_ASSERT_NULL(manufacturer_id, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_manufacturer_id, manufacturer_id, cmock_call_instance->Expected_manufacturer_id_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.BoardInfo_decodeBase64ManufacturerId_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.BoardInfo_decodeBase64ManufacturerId_CallbackFunctionPointer(manufacturer_id, Mock.BoardInfo_decodeBase64ManufacturerId_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_manufacturer_id_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(manufacturer_id, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)manufacturer_id, (const void*)cmock_call_instance->ReturnThruPtr_manufacturer_id_Val,
      cmock_call_instance->ReturnThruPtr_manufacturer_id_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_BoardInfo_decodeBase64ManufacturerId(CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE* cmock_call_instance, uint8_t* manufacturer_id, int manufacturer_id_Depth);
void CMockExpectParameters_BoardInfo_decodeBase64ManufacturerId(CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE* cmock_call_instance, uint8_t* manufacturer_id, int manufacturer_id_Depth)
{
  cmock_call_instance->Expected_manufacturer_id = manufacturer_id;
  cmock_call_instance->Expected_manufacturer_id_Depth = manufacturer_id_Depth;
  cmock_call_instance->IgnoreArg_manufacturer_id = 0;
  cmock_call_instance->ReturnThruPtr_manufacturer_id_Used = 0;
}

void BoardInfo_decodeBase64ManufacturerId_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE));
  CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE* cmock_call_instance = (CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BoardInfo_decodeBase64ManufacturerId_CallInstance = CMock_Guts_MemChain(Mock.BoardInfo_decodeBase64ManufacturerId_CallInstance, cmock_guts_index);
  Mock.BoardInfo_decodeBase64ManufacturerId_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.BoardInfo_decodeBase64ManufacturerId_IgnoreBool = (char)1;
}

void BoardInfo_decodeBase64ManufacturerId_CMockStopIgnore(void)
{
  if(Mock.BoardInfo_decodeBase64ManufacturerId_IgnoreBool)
    Mock.BoardInfo_decodeBase64ManufacturerId_CallInstance = CMock_Guts_MemNext(Mock.BoardInfo_decodeBase64ManufacturerId_CallInstance);
  Mock.BoardInfo_decodeBase64ManufacturerId_IgnoreBool = (char)0;
}

void BoardInfo_decodeBase64ManufacturerId_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE));
  CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE* cmock_call_instance = (CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BoardInfo_decodeBase64ManufacturerId_CallInstance = CMock_Guts_MemChain(Mock.BoardInfo_decodeBase64ManufacturerId_CallInstance, cmock_guts_index);
  Mock.BoardInfo_decodeBase64ManufacturerId_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void BoardInfo_decodeBase64ManufacturerId_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* manufacturer_id, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE));
  CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE* cmock_call_instance = (CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BoardInfo_decodeBase64ManufacturerId_CallInstance = CMock_Guts_MemChain(Mock.BoardInfo_decodeBase64ManufacturerId_CallInstance, cmock_guts_index);
  Mock.BoardInfo_decodeBase64ManufacturerId_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_BoardInfo_decodeBase64ManufacturerId(cmock_call_instance, manufacturer_id, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void BoardInfo_decodeBase64ManufacturerId_AddCallback(CMOCK_BoardInfo_decodeBase64ManufacturerId_CALLBACK Callback)
{
  Mock.BoardInfo_decodeBase64ManufacturerId_IgnoreBool = (char)0;
  Mock.BoardInfo_decodeBase64ManufacturerId_CallbackBool = (char)1;
  Mock.BoardInfo_decodeBase64ManufacturerId_CallbackFunctionPointer = Callback;
}

void BoardInfo_decodeBase64ManufacturerId_Stub(CMOCK_BoardInfo_decodeBase64ManufacturerId_CALLBACK Callback)
{
  Mock.BoardInfo_decodeBase64ManufacturerId_IgnoreBool = (char)0;
  Mock.BoardInfo_decodeBase64ManufacturerId_CallbackBool = (char)0;
  Mock.BoardInfo_decodeBase64ManufacturerId_CallbackFunctionPointer = Callback;
}

void BoardInfo_decodeBase64ManufacturerId_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t* manufacturer_id, int manufacturer_id_Depth, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE));
  CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE* cmock_call_instance = (CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.BoardInfo_decodeBase64ManufacturerId_CallInstance = CMock_Guts_MemChain(Mock.BoardInfo_decodeBase64ManufacturerId_CallInstance, cmock_guts_index);
  Mock.BoardInfo_decodeBase64ManufacturerId_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_BoardInfo_decodeBase64ManufacturerId(cmock_call_instance, manufacturer_id, manufacturer_id_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void BoardInfo_decodeBase64ManufacturerId_CMockReturnMemThruPtr_manufacturer_id(UNITY_LINE_TYPE cmock_line, uint8_t const* manufacturer_id, size_t cmock_size)
{
  CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE* cmock_call_instance = (CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.BoardInfo_decodeBase64ManufacturerId_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_manufacturer_id_Used = 1;
  cmock_call_instance->ReturnThruPtr_manufacturer_id_Val = manufacturer_id;
  cmock_call_instance->ReturnThruPtr_manufacturer_id_Size = cmock_size;
}

void BoardInfo_decodeBase64ManufacturerId_CMockIgnoreArg_manufacturer_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE* cmock_call_instance = (CMOCK_BoardInfo_decodeBase64ManufacturerId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.BoardInfo_decodeBase64ManufacturerId_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_manufacturer_id = 1;
}

