name: Checks

on:
  push:
    branches: 
    - 'master'
  pull_request:
    branches:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: px4io/px4-dev-nuttx-focal:2021-09-08
      options: --privileged --ulimit core=-1 --security-opt seccomp=unconfined

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Check format
      run: make check_format

    - name: Check MISRA C:2012
      run: make misra
