name: Checks

on:
  push:
    branches: 
    - 'master'
  pull_request:
    branches:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: igormisic/improject:v1.0.2
      options: --privileged --ulimit core=-1 --security-opt seccomp=unconfined

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Mark repository as safe
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Check format
      run: make check_format

    - name: Check MISRA C:2012
      run: make misra
