name: Compile targets

on:
  push:
    branches: 
    - 'master'
  pull_request:
    branches:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: [
          stm32l4xx,
          stm32f7xx,
          stm32f7xx_ram,
          stm32h7xx,
          stm32h7xx secure=true,
          stm32h7xx_ram,
          stm32h7xx_ram secure=true,
          matek_H7_slim,
          matek_H7_slim secure=true,
          matek_H7_slim_ram,
          matek_H7_slim_ram secure=true,
          pixhawk4,
          pixhawk4_ram
          ]
          
    container:       
      image: px4io/px4-dev-nuttx-focal:2021-09-08
      options: --privileged --ulimit core=-1 --security-opt seccomp=unconfined
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: 'true'
      
    - name: make ${{matrix.config}}
      run: make ${{matrix.config}}
